/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * The version of the OpenAPI document: 1.2.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
  * @typedef {Object} IAssetsControllerApiAssetUsage
  * @property {String} assetId
  * @property {String} namespace
  * @property {String} flowId
  * @property {Number} flowRevision
  * @property {String} executionId
  * @property {String} taskId
  * @property {String} taskRunId
  * @property {Date} created
  */

/**
 * The AssetsControllerApiAssetUsage model module.
 * @module model/AssetsControllerApiAssetUsage
 * @type {IAssetsControllerApiAssetUsage}
 */
class AssetsControllerApiAssetUsage {
    /**
     * Constructs a new <code>AssetsControllerApiAssetUsage</code>.
     * @alias module:model/AssetsControllerApiAssetUsage
     */
    constructor() { 
        
        AssetsControllerApiAssetUsage.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AssetsControllerApiAssetUsage</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AssetsControllerApiAssetUsage} obj Optional instance to populate.
     * @return {module:model/AssetsControllerApiAssetUsage} The populated <code>AssetsControllerApiAssetUsage</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AssetsControllerApiAssetUsage();

            if (data.hasOwnProperty('assetId')) {
                obj['assetId'] = ApiClient.convertToType(data['assetId'], 'String');
            }
            if (data.hasOwnProperty('namespace')) {
                obj['namespace'] = ApiClient.convertToType(data['namespace'], 'String');
            }
            if (data.hasOwnProperty('flowId')) {
                obj['flowId'] = ApiClient.convertToType(data['flowId'], 'String');
            }
            if (data.hasOwnProperty('flowRevision')) {
                obj['flowRevision'] = ApiClient.convertToType(data['flowRevision'], 'Number');
            }
            if (data.hasOwnProperty('executionId')) {
                obj['executionId'] = ApiClient.convertToType(data['executionId'], 'String');
            }
            if (data.hasOwnProperty('taskId')) {
                obj['taskId'] = ApiClient.convertToType(data['taskId'], 'String');
            }
            if (data.hasOwnProperty('taskRunId')) {
                obj['taskRunId'] = ApiClient.convertToType(data['taskRunId'], 'String');
            }
            if (data.hasOwnProperty('created')) {
                obj['created'] = ApiClient.convertToType(data['created'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AssetsControllerApiAssetUsage</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AssetsControllerApiAssetUsage</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['assetId'] && !(typeof data['assetId'] === 'string' || data['assetId'] instanceof String)) {
            throw new Error("Expected the field `assetId` to be a primitive type in the JSON string but got " + data['assetId']);
        }
        // ensure the json data is a string
        if (data['namespace'] && !(typeof data['namespace'] === 'string' || data['namespace'] instanceof String)) {
            throw new Error("Expected the field `namespace` to be a primitive type in the JSON string but got " + data['namespace']);
        }
        // ensure the json data is a string
        if (data['flowId'] && !(typeof data['flowId'] === 'string' || data['flowId'] instanceof String)) {
            throw new Error("Expected the field `flowId` to be a primitive type in the JSON string but got " + data['flowId']);
        }
        // ensure the json data is a string
        if (data['executionId'] && !(typeof data['executionId'] === 'string' || data['executionId'] instanceof String)) {
            throw new Error("Expected the field `executionId` to be a primitive type in the JSON string but got " + data['executionId']);
        }
        // ensure the json data is a string
        if (data['taskId'] && !(typeof data['taskId'] === 'string' || data['taskId'] instanceof String)) {
            throw new Error("Expected the field `taskId` to be a primitive type in the JSON string but got " + data['taskId']);
        }
        // ensure the json data is a string
        if (data['taskRunId'] && !(typeof data['taskRunId'] === 'string' || data['taskRunId'] instanceof String)) {
            throw new Error("Expected the field `taskRunId` to be a primitive type in the JSON string but got " + data['taskRunId']);
        }

        return true;
    }


}



/**
 * @member {String} assetId
 */
AssetsControllerApiAssetUsage.prototype['assetId'] = undefined;

/**
 * @member {String} namespace
 */
AssetsControllerApiAssetUsage.prototype['namespace'] = undefined;

/**
 * @member {String} flowId
 */
AssetsControllerApiAssetUsage.prototype['flowId'] = undefined;

/**
 * @member {Number} flowRevision
 */
AssetsControllerApiAssetUsage.prototype['flowRevision'] = undefined;

/**
 * @member {String} executionId
 */
AssetsControllerApiAssetUsage.prototype['executionId'] = undefined;

/**
 * @member {String} taskId
 */
AssetsControllerApiAssetUsage.prototype['taskId'] = undefined;

/**
 * @member {String} taskRunId
 */
AssetsControllerApiAssetUsage.prototype['taskRunId'] = undefined;

/**
 * @member {Date} created
 */
AssetsControllerApiAssetUsage.prototype['created'] = undefined;






export default AssetsControllerApiAssetUsage;

