/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PasswordConfigurationPasswordReset from './PasswordConfigurationPasswordReset';

/**
  * @typedef {Object} IPasswordConfiguration
  * @property {Number} passwordMinLength
  * @property {Boolean} passwordRequireSpecial
  * @property {Number} passwordMinDigits
  * @property {Number} passwordMinLowerCase
  * @property {Number} passwordMinUpperCase
  * @property {String} passwordAllowedSpecialCharacters
  * @property {PasswordConfigurationPasswordReset} passwordReset
  */

/**
 * The PasswordConfiguration model module.
 * @module model/PasswordConfiguration
 * @type {IPasswordConfiguration}
 */
class PasswordConfiguration {
    /**
     * Constructs a new <code>PasswordConfiguration</code>.
     * @alias module:model/PasswordConfiguration
     */
    constructor() { 
        
        PasswordConfiguration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['passwordMinLength'] = 8;
        obj['passwordRequireSpecial'] = true;
        obj['passwordMinDigits'] = 1;
        obj['passwordMinLowerCase'] = 1;
        obj['passwordMinUpperCase'] = 1;
        obj['passwordAllowedSpecialCharacters'] = '!@#$%^&*';
    }

    /**
     * Constructs a <code>PasswordConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PasswordConfiguration} obj Optional instance to populate.
     * @return {module:model/PasswordConfiguration} The populated <code>PasswordConfiguration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PasswordConfiguration();

            if (data.hasOwnProperty('passwordMinLength')) {
                obj['passwordMinLength'] = ApiClient.convertToType(data['passwordMinLength'], 'Number');
            }
            if (data.hasOwnProperty('passwordRequireSpecial')) {
                obj['passwordRequireSpecial'] = ApiClient.convertToType(data['passwordRequireSpecial'], 'Boolean');
            }
            if (data.hasOwnProperty('passwordMinDigits')) {
                obj['passwordMinDigits'] = ApiClient.convertToType(data['passwordMinDigits'], 'Number');
            }
            if (data.hasOwnProperty('passwordMinLowerCase')) {
                obj['passwordMinLowerCase'] = ApiClient.convertToType(data['passwordMinLowerCase'], 'Number');
            }
            if (data.hasOwnProperty('passwordMinUpperCase')) {
                obj['passwordMinUpperCase'] = ApiClient.convertToType(data['passwordMinUpperCase'], 'Number');
            }
            if (data.hasOwnProperty('passwordAllowedSpecialCharacters')) {
                obj['passwordAllowedSpecialCharacters'] = ApiClient.convertToType(data['passwordAllowedSpecialCharacters'], 'String');
            }
            if (data.hasOwnProperty('passwordReset')) {
                obj['passwordReset'] = PasswordConfigurationPasswordReset.constructFromObject(data['passwordReset']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PasswordConfiguration</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PasswordConfiguration</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['passwordAllowedSpecialCharacters'] && !(typeof data['passwordAllowedSpecialCharacters'] === 'string' || data['passwordAllowedSpecialCharacters'] instanceof String)) {
            throw new Error("Expected the field `passwordAllowedSpecialCharacters` to be a primitive type in the JSON string but got " + data['passwordAllowedSpecialCharacters']);
        }
        // validate the optional field `passwordReset`
        if (data['passwordReset']) { // data not null
          PasswordConfigurationPasswordReset.validateJSON(data['passwordReset']);
        }

        return true;
    }


}



/**
 * @member {Number} passwordMinLength
 * @default 8
 */
PasswordConfiguration.prototype['passwordMinLength'] = 8;

/**
 * @member {Boolean} passwordRequireSpecial
 * @default true
 */
PasswordConfiguration.prototype['passwordRequireSpecial'] = true;

/**
 * @member {Number} passwordMinDigits
 * @default 1
 */
PasswordConfiguration.prototype['passwordMinDigits'] = 1;

/**
 * @member {Number} passwordMinLowerCase
 * @default 1
 */
PasswordConfiguration.prototype['passwordMinLowerCase'] = 1;

/**
 * @member {Number} passwordMinUpperCase
 * @default 1
 */
PasswordConfiguration.prototype['passwordMinUpperCase'] = 1;

/**
 * @member {String} passwordAllowedSpecialCharacters
 * @default '!@#$%^&*'
 */
PasswordConfiguration.prototype['passwordAllowedSpecialCharacters'] = '!@#$%^&*';

/**
 * @member {module:model/PasswordConfigurationPasswordReset} passwordReset
 */
PasswordConfiguration.prototype['passwordReset'] = undefined;






export default PasswordConfiguration;

