/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
  * @typedef {Object} IPluginPluginElementMetadata
  * @property {String} cls
  * @property {Boolean} deprecated
  * @property {String} title
  * @property {String} description
  */

/**
 * The PluginPluginElementMetadata model module.
 * @module model/PluginPluginElementMetadata
 * @type {IPluginPluginElementMetadata}
 */
class PluginPluginElementMetadata {
    /**
     * Constructs a new <code>PluginPluginElementMetadata</code>.
     * @alias module:model/PluginPluginElementMetadata
     */
    constructor() { 
        
        PluginPluginElementMetadata.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>PluginPluginElementMetadata</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PluginPluginElementMetadata} obj Optional instance to populate.
     * @return {module:model/PluginPluginElementMetadata} The populated <code>PluginPluginElementMetadata</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PluginPluginElementMetadata();

            if (data.hasOwnProperty('cls')) {
                obj['cls'] = ApiClient.convertToType(data['cls'], 'String');
            }
            if (data.hasOwnProperty('deprecated')) {
                obj['deprecated'] = ApiClient.convertToType(data['deprecated'], 'Boolean');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PluginPluginElementMetadata</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PluginPluginElementMetadata</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['cls'] && !(typeof data['cls'] === 'string' || data['cls'] instanceof String)) {
            throw new Error("Expected the field `cls` to be a primitive type in the JSON string but got " + data['cls']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * @member {String} cls
 */
PluginPluginElementMetadata.prototype['cls'] = undefined;

/**
 * @member {Boolean} deprecated
 */
PluginPluginElementMetadata.prototype['deprecated'] = undefined;

/**
 * @member {String} title
 */
PluginPluginElementMetadata.prototype['title'] = undefined;

/**
 * @member {String} description
 */
PluginPluginElementMetadata.prototype['description'] = undefined;






export default PluginPluginElementMetadata;

