/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StateHistory from './StateHistory';
import StateType from './StateType';

/**
  * @typedef {Object} IState
  * @property {String} duration
  * @property {Date} startDate
  * @property {Date} endDate
  * @property {keyof typeof import('./StateType').StateTypeStatic} current
  * @property {Array.<module:model/StateHistory>} histories
  * @property {String} getDuration
  * @property {Date} getStartDate
  * @property {Date} getEndDate
  */

/**
 * The State model module.
 * @module model/State
 * @type {IState}
 */
class State {
    /**
     * Constructs a new <code>State</code>.
     * @alias module:model/State
     * @param {module:model/StateType} current - 
     * @param {String} getDuration - 
     * @param {Date} getStartDate - 
     * @param {Date} getEndDate - 
     */
    constructor(current, getDuration, getStartDate, getEndDate) { 
        
        State.initialize(this, current, getDuration, getStartDate, getEndDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, current, getDuration, getStartDate, getEndDate) { 
        obj['current'] = current;
        obj['getDuration'] = getDuration;
        obj['getStartDate'] = getStartDate;
        obj['getEndDate'] = getEndDate;
    }

    /**
     * Constructs a <code>State</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/State} obj Optional instance to populate.
     * @return {module:model/State} The populated <code>State</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new State();

            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], 'String');
            }
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
            }
            if (data.hasOwnProperty('endDate')) {
                obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
            }
            if (data.hasOwnProperty('current')) {
                obj['current'] = StateType.constructFromObject(data['current']);
            }
            if (data.hasOwnProperty('histories')) {
                obj['histories'] = ApiClient.convertToType(data['histories'], [StateHistory]);
            }
            if (data.hasOwnProperty('getDuration')) {
                obj['getDuration'] = ApiClient.convertToType(data['getDuration'], 'String');
            }
            if (data.hasOwnProperty('getStartDate')) {
                obj['getStartDate'] = ApiClient.convertToType(data['getStartDate'], 'Date');
            }
            if (data.hasOwnProperty('getEndDate')) {
                obj['getEndDate'] = ApiClient.convertToType(data['getEndDate'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>State</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>State</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of State.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['duration'] && !(typeof data['duration'] === 'string' || data['duration'] instanceof String)) {
            throw new Error("Expected the field `duration` to be a primitive type in the JSON string but got " + data['duration']);
        }
        if (data['histories']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['histories'])) {
                throw new Error("Expected the field `histories` to be an array in the JSON data but got " + data['histories']);
            }
            // validate the optional field `histories` (array)
            for (const item of data['histories']) {
                StateHistory.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['getDuration'] && !(typeof data['getDuration'] === 'string' || data['getDuration'] instanceof String)) {
            throw new Error("Expected the field `getDuration` to be a primitive type in the JSON string but got " + data['getDuration']);
        }

        return true;
    }


}

State.RequiredProperties = ["current", "getDuration", "getStartDate", "getEndDate"];

/**
 * @member {String} duration
 */
State.prototype['duration'] = undefined;

/**
 * @member {Date} startDate
 */
State.prototype['startDate'] = undefined;

/**
 * @member {Date} endDate
 */
State.prototype['endDate'] = undefined;

/**
 * @member {module:model/StateType} current
 */
State.prototype['current'] = undefined;

/**
 * @member {Array.<module:model/StateHistory>} histories
 */
State.prototype['histories'] = undefined;

/**
 * @member {String} getDuration
 */
State.prototype['getDuration'] = undefined;

/**
 * @member {Date} getStartDate
 */
State.prototype['getStartDate'] = undefined;

/**
 * @member {Date} getEndDate
 */
State.prototype['getEndDate'] = undefined;






export default State;

