/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
 * Enum SupportDebugInfoAuthType
 * @type {{
 *   "OIDC_SSO": "OIDC_SSO","LDAP": "LDAP","BASIC_AUTH": "BASIC_AUTH",
 * }}
 */
export const SupportDebugInfoAuthTypeStatic = { 
    "OIDC_SSO": "OIDC_SSO",
    "LDAP": "LDAP",
    "BASIC_AUTH": "BASIC_AUTH",
}

/**
* Enum class SupportDebugInfoAuthType.
* @enum {}
* @readonly
*/
export default class SupportDebugInfoAuthType {
    
        /**
         * value: "OIDC_SSO"
         * @const
         */
        "OIDC_SSO" = "OIDC_SSO";

    
        /**
         * value: "LDAP"
         * @const
         */
        "LDAP" = "LDAP";

    
        /**
         * value: "BASIC_AUTH"
         * @const
         */
        "BASIC_AUTH" = "BASIC_AUTH";

    

    /**
    * Returns a <code>SupportDebugInfoAuthType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/SupportDebugInfoAuthType} The enum <code>SupportDebugInfoAuthType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

