/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
	"fmt"
)

// Relation1 the model 'Relation1'
type Relation1 string

// List of Relation_1
const (
	RELATION1_UPSERT  Relation1 = "UPSERT"
	RELATION1_USED_BY Relation1 = "USED_BY"
)

// All allowed values of Relation1 enum
var AllowedRelation1EnumValues = []Relation1{
	"UPSERT",
	"USED_BY",
}

func (v *Relation1) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Relation1(value)
	for _, existing := range AllowedRelation1EnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Relation1", value)
}

// NewRelation1FromValue returns a pointer to a valid Relation1
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRelation1FromValue(v string) (*Relation1, error) {
	ev := Relation1(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Relation1: valid values are %v", v, AllowedRelation1EnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Relation1) IsValid() bool {
	for _, existing := range AllowedRelation1EnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Relation_1 value
func (v Relation1) Ptr() *Relation1 {
	return &v
}

type NullableRelation1 struct {
	value *Relation1
	isSet bool
}

func (v NullableRelation1) Get() *Relation1 {
	return v.value
}

func (v *NullableRelation1) Set(val *Relation1) {
	v.value = val
	v.isSet = true
}

func (v NullableRelation1) IsSet() bool {
	return v.isSet
}

func (v *NullableRelation1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRelation1(val *Relation1) *NullableRelation1 {
	return &NullableRelation1{value: val, isSet: true}
}

func (v NullableRelation1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRelation1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
