/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
	"time"
)

// checks if the AssetsControllerApiAssetUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AssetsControllerApiAssetUsage{}

// AssetsControllerApiAssetUsage struct for AssetsControllerApiAssetUsage
type AssetsControllerApiAssetUsage struct {
	AssetId              *string    `json:"assetId,omitempty"`
	Namespace            *string    `json:"namespace,omitempty"`
	FlowId               *string    `json:"flowId,omitempty"`
	FlowRevision         *int32     `json:"flowRevision,omitempty"`
	ExecutionId          *string    `json:"executionId,omitempty"`
	TaskId               *string    `json:"taskId,omitempty"`
	TaskRunId            *string    `json:"taskRunId,omitempty"`
	Created              *time.Time `json:"created,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AssetsControllerApiAssetUsage AssetsControllerApiAssetUsage

// NewAssetsControllerApiAssetUsage instantiates a new AssetsControllerApiAssetUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssetsControllerApiAssetUsage() *AssetsControllerApiAssetUsage {
	this := AssetsControllerApiAssetUsage{}
	return &this
}

// NewAssetsControllerApiAssetUsageWithDefaults instantiates a new AssetsControllerApiAssetUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssetsControllerApiAssetUsageWithDefaults() *AssetsControllerApiAssetUsage {
	this := AssetsControllerApiAssetUsage{}
	return &this
}

// GetAssetId returns the AssetId field value if set, zero value otherwise.
func (o *AssetsControllerApiAssetUsage) GetAssetId() string {
	if o == nil || IsNil(o.AssetId) {
		var ret string
		return ret
	}
	return *o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsControllerApiAssetUsage) GetAssetIdOk() (*string, bool) {
	if o == nil || IsNil(o.AssetId) {
		return nil, false
	}
	return o.AssetId, true
}

// HasAssetId returns a boolean if a field has been set.
func (o *AssetsControllerApiAssetUsage) HasAssetId() bool {
	if o != nil && !IsNil(o.AssetId) {
		return true
	}

	return false
}

// SetAssetId gets a reference to the given string and assigns it to the AssetId field.
func (o *AssetsControllerApiAssetUsage) SetAssetId(v string) {
	o.AssetId = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *AssetsControllerApiAssetUsage) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsControllerApiAssetUsage) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *AssetsControllerApiAssetUsage) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *AssetsControllerApiAssetUsage) SetNamespace(v string) {
	o.Namespace = &v
}

// GetFlowId returns the FlowId field value if set, zero value otherwise.
func (o *AssetsControllerApiAssetUsage) GetFlowId() string {
	if o == nil || IsNil(o.FlowId) {
		var ret string
		return ret
	}
	return *o.FlowId
}

// GetFlowIdOk returns a tuple with the FlowId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsControllerApiAssetUsage) GetFlowIdOk() (*string, bool) {
	if o == nil || IsNil(o.FlowId) {
		return nil, false
	}
	return o.FlowId, true
}

// HasFlowId returns a boolean if a field has been set.
func (o *AssetsControllerApiAssetUsage) HasFlowId() bool {
	if o != nil && !IsNil(o.FlowId) {
		return true
	}

	return false
}

// SetFlowId gets a reference to the given string and assigns it to the FlowId field.
func (o *AssetsControllerApiAssetUsage) SetFlowId(v string) {
	o.FlowId = &v
}

// GetFlowRevision returns the FlowRevision field value if set, zero value otherwise.
func (o *AssetsControllerApiAssetUsage) GetFlowRevision() int32 {
	if o == nil || IsNil(o.FlowRevision) {
		var ret int32
		return ret
	}
	return *o.FlowRevision
}

// GetFlowRevisionOk returns a tuple with the FlowRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsControllerApiAssetUsage) GetFlowRevisionOk() (*int32, bool) {
	if o == nil || IsNil(o.FlowRevision) {
		return nil, false
	}
	return o.FlowRevision, true
}

// HasFlowRevision returns a boolean if a field has been set.
func (o *AssetsControllerApiAssetUsage) HasFlowRevision() bool {
	if o != nil && !IsNil(o.FlowRevision) {
		return true
	}

	return false
}

// SetFlowRevision gets a reference to the given int32 and assigns it to the FlowRevision field.
func (o *AssetsControllerApiAssetUsage) SetFlowRevision(v int32) {
	o.FlowRevision = &v
}

// GetExecutionId returns the ExecutionId field value if set, zero value otherwise.
func (o *AssetsControllerApiAssetUsage) GetExecutionId() string {
	if o == nil || IsNil(o.ExecutionId) {
		var ret string
		return ret
	}
	return *o.ExecutionId
}

// GetExecutionIdOk returns a tuple with the ExecutionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsControllerApiAssetUsage) GetExecutionIdOk() (*string, bool) {
	if o == nil || IsNil(o.ExecutionId) {
		return nil, false
	}
	return o.ExecutionId, true
}

// HasExecutionId returns a boolean if a field has been set.
func (o *AssetsControllerApiAssetUsage) HasExecutionId() bool {
	if o != nil && !IsNil(o.ExecutionId) {
		return true
	}

	return false
}

// SetExecutionId gets a reference to the given string and assigns it to the ExecutionId field.
func (o *AssetsControllerApiAssetUsage) SetExecutionId(v string) {
	o.ExecutionId = &v
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *AssetsControllerApiAssetUsage) GetTaskId() string {
	if o == nil || IsNil(o.TaskId) {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsControllerApiAssetUsage) GetTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *AssetsControllerApiAssetUsage) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *AssetsControllerApiAssetUsage) SetTaskId(v string) {
	o.TaskId = &v
}

// GetTaskRunId returns the TaskRunId field value if set, zero value otherwise.
func (o *AssetsControllerApiAssetUsage) GetTaskRunId() string {
	if o == nil || IsNil(o.TaskRunId) {
		var ret string
		return ret
	}
	return *o.TaskRunId
}

// GetTaskRunIdOk returns a tuple with the TaskRunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsControllerApiAssetUsage) GetTaskRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskRunId) {
		return nil, false
	}
	return o.TaskRunId, true
}

// HasTaskRunId returns a boolean if a field has been set.
func (o *AssetsControllerApiAssetUsage) HasTaskRunId() bool {
	if o != nil && !IsNil(o.TaskRunId) {
		return true
	}

	return false
}

// SetTaskRunId gets a reference to the given string and assigns it to the TaskRunId field.
func (o *AssetsControllerApiAssetUsage) SetTaskRunId(v string) {
	o.TaskRunId = &v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *AssetsControllerApiAssetUsage) GetCreated() time.Time {
	if o == nil || IsNil(o.Created) {
		var ret time.Time
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssetsControllerApiAssetUsage) GetCreatedOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *AssetsControllerApiAssetUsage) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given time.Time and assigns it to the Created field.
func (o *AssetsControllerApiAssetUsage) SetCreated(v time.Time) {
	o.Created = &v
}

func (o AssetsControllerApiAssetUsage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AssetsControllerApiAssetUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AssetId) {
		toSerialize["assetId"] = o.AssetId
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.FlowId) {
		toSerialize["flowId"] = o.FlowId
	}
	if !IsNil(o.FlowRevision) {
		toSerialize["flowRevision"] = o.FlowRevision
	}
	if !IsNil(o.ExecutionId) {
		toSerialize["executionId"] = o.ExecutionId
	}
	if !IsNil(o.TaskId) {
		toSerialize["taskId"] = o.TaskId
	}
	if !IsNil(o.TaskRunId) {
		toSerialize["taskRunId"] = o.TaskRunId
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AssetsControllerApiAssetUsage) UnmarshalJSON(data []byte) (err error) {
	varAssetsControllerApiAssetUsage := _AssetsControllerApiAssetUsage{}

	err = json.Unmarshal(data, &varAssetsControllerApiAssetUsage)

	if err != nil {
		return err
	}

	*o = AssetsControllerApiAssetUsage(varAssetsControllerApiAssetUsage)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "assetId")
		delete(additionalProperties, "namespace")
		delete(additionalProperties, "flowId")
		delete(additionalProperties, "flowRevision")
		delete(additionalProperties, "executionId")
		delete(additionalProperties, "taskId")
		delete(additionalProperties, "taskRunId")
		delete(additionalProperties, "created")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAssetsControllerApiAssetUsage struct {
	value *AssetsControllerApiAssetUsage
	isSet bool
}

func (v NullableAssetsControllerApiAssetUsage) Get() *AssetsControllerApiAssetUsage {
	return v.value
}

func (v *NullableAssetsControllerApiAssetUsage) Set(val *AssetsControllerApiAssetUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableAssetsControllerApiAssetUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableAssetsControllerApiAssetUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssetsControllerApiAssetUsage(val *AssetsControllerApiAssetUsage) *NullableAssetsControllerApiAssetUsage {
	return &NullableAssetsControllerApiAssetUsage{value: val, isSet: true}
}

func (v NullableAssetsControllerApiAssetUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssetsControllerApiAssetUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
