/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

API version: 1.2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
	"fmt"

	"gopkg.in/validator.v2"
)

// PropertyString - struct for PropertyString
type PropertyString struct {
	MapmapOfStringAny *map[string]interface{}
	String            *string
}

// map[string]interface{}AsPropertyString is a convenience function that returns map[string]interface{} wrapped in PropertyString
func MapmapOfStringAnyAsPropertyString(v *map[string]interface{}) PropertyString {
	return PropertyString{
		MapmapOfStringAny: v,
	}
}

// stringAsPropertyString is a convenience function that returns string wrapped in PropertyString
func StringAsPropertyString(v *string) PropertyString {
	return PropertyString{
		String: v,
	}
}

// Unmarshal JSON data into one of the pointers in the struct
func (dst *PropertyString) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into MapmapOfStringAny
	err = newStrictDecoder(data).Decode(&dst.MapmapOfStringAny)
	if err == nil {
		jsonMapmapOfStringAny, _ := json.Marshal(dst.MapmapOfStringAny)
		if string(jsonMapmapOfStringAny) == "{}" { // empty struct
			dst.MapmapOfStringAny = nil
		} else {
			if err = validator.Validate(dst.MapmapOfStringAny); err != nil {
				dst.MapmapOfStringAny = nil
			} else {
				match++
			}
		}
	} else {
		dst.MapmapOfStringAny = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.MapmapOfStringAny = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PropertyString)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PropertyString)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PropertyString) MarshalJSON() ([]byte, error) {
	if src.MapmapOfStringAny != nil {
		return json.Marshal(&src.MapmapOfStringAny)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PropertyString) GetActualInstance() interface{} {
	if obj == nil {
		return nil
	}
	if obj.MapmapOfStringAny != nil {
		return obj.MapmapOfStringAny
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PropertyString) GetActualInstanceValue() interface{} {
	if obj.MapmapOfStringAny != nil {
		return *obj.MapmapOfStringAny
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullablePropertyString struct {
	value *PropertyString
	isSet bool
}

func (v NullablePropertyString) Get() *PropertyString {
	return v.value
}

func (v *NullablePropertyString) Set(val *PropertyString) {
	v.value = val
	v.isSet = true
}

func (v NullablePropertyString) IsSet() bool {
	return v.isSet
}

func (v *NullablePropertyString) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePropertyString(val *PropertyString) *NullablePropertyString {
	return &NullablePropertyString{value: val, isSet: true}
}

func (v NullablePropertyString) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePropertyString) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
