/**
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * The version of the OpenAPI document: 1.1.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import { describe, it, beforeEach } from 'vitest';
import KestraClient from "../../src/KestraClient"

let instance;

beforeEach(function() {
    instance = new KestraClient().rolesApi;
});

let getProperty = function(object, getter, property) {
// Use getter method if present; otherwise, get the property directly.
if (typeof object[getter] === 'function')
    return object[getter]();
else
    return object[property];
}

var setProperty = function(object, setter, property, value) {
// Use setter method if present; otherwise, set the property directly.
if (typeof object[setter] === 'function')
    object[setter](value);
else
    object[property] = value;
}

describe('RolesApi', function() {
    describe('autocompleteRoles', function() {
        it('should call autocompleteRoles successfully', function() {
            //uncomment below and update the code to test autocompleteRoles
            //instance.autocompleteRoles(function(error) {
            //  if (error) throw error;
            //expect().to.be();
            //});
        });
    });
    describe('createRole', function() {
        it('should call createRole successfully', function() {
            //uncomment below and update the code to test createRole
            //instance.createRole(function(error) {
            //  if (error) throw error;
            //expect().to.be();
            //});
        });
    });
    describe('deleteRole', function() {
        it('should call deleteRole successfully', function() {
            //uncomment below and update the code to test deleteRole
            //instance.deleteRole(function(error) {
            //  if (error) throw error;
            //expect().to.be();
            //});
        });
    });
    describe('listRolesFromGivenIds', function() {
        it('should call listRolesFromGivenIds successfully', function() {
            //uncomment below and update the code to test listRolesFromGivenIds
            //instance.listRolesFromGivenIds(function(error) {
            //  if (error) throw error;
            //expect().to.be();
            //});
        });
    });
    describe('role', function() {
        it('should call role successfully', function() {
            //uncomment below and update the code to test role
            //instance.role(function(error) {
            //  if (error) throw error;
            //expect().to.be();
            //});
        });
    });
    describe('searchRoles', function() {
        it('should call searchRoles successfully', function() {
            //uncomment below and update the code to test searchRoles
            //instance.searchRoles(function(error) {
            //  if (error) throw error;
            //expect().to.be();
            //});
        });
    });
    describe('updateRole', function() {
        it('should call updateRole successfully', function() {
            //uncomment below and update the code to test updateRole
            //instance.updateRole(function(error) {
            //  if (error) throw error;
            //expect().to.be();
            //});
        });
    });
});
