/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

API version: 2.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
	"fmt"
)

// AuthPropertyType the model 'AuthPropertyType'
type AuthPropertyType string

// List of AuthProperty.Type
const (
	AUTHPROPERTYTYPE_VALUE AuthPropertyType = "VALUE"
	AUTHPROPERTYTYPE_SECRET AuthPropertyType = "SECRET"
)

// All allowed values of AuthPropertyType enum
var AllowedAuthPropertyTypeEnumValues = []AuthPropertyType{
	"VALUE",
	"SECRET",
}

func (v *AuthPropertyType) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := AuthPropertyType(value)
	for _, existing := range AllowedAuthPropertyTypeEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid AuthPropertyType", value)
}

// NewAuthPropertyTypeFromValue returns a pointer to a valid AuthPropertyType
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewAuthPropertyTypeFromValue(v string) (*AuthPropertyType, error) {
	ev := AuthPropertyType(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for AuthPropertyType: valid values are %v", v, AllowedAuthPropertyTypeEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v AuthPropertyType) IsValid() bool {
	for _, existing := range AllowedAuthPropertyTypeEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to AuthProperty.Type value
func (v AuthPropertyType) Ptr() *AuthPropertyType {
	return &v
}

type NullableAuthPropertyType struct {
	value *AuthPropertyType
	isSet bool
}

func (v NullableAuthPropertyType) Get() *AuthPropertyType {
	return v.value
}

func (v *NullableAuthPropertyType) Set(val *AuthPropertyType) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthPropertyType) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthPropertyType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthPropertyType(val *AuthPropertyType) *NullableAuthPropertyType {
	return &NullableAuthPropertyType{value: val, isSet: true}
}

func (v NullableAuthPropertyType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthPropertyType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

