/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
	"fmt"
)

// checks if the AiControllerFlowGenerationPrompt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AiControllerFlowGenerationPrompt{}

// AiControllerFlowGenerationPrompt struct for AiControllerFlowGenerationPrompt
type AiControllerFlowGenerationPrompt struct {
	ConversationId string `json:"conversationId"`
	UserPrompt string `json:"userPrompt"`
	Yaml *string `json:"yaml,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
	ProviderId *string `json:"providerId,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AiControllerFlowGenerationPrompt AiControllerFlowGenerationPrompt

// NewAiControllerFlowGenerationPrompt instantiates a new AiControllerFlowGenerationPrompt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAiControllerFlowGenerationPrompt(conversationId string, userPrompt string) *AiControllerFlowGenerationPrompt {
	this := AiControllerFlowGenerationPrompt{}
	this.ConversationId = conversationId
	this.UserPrompt = userPrompt
	return &this
}

// NewAiControllerFlowGenerationPromptWithDefaults instantiates a new AiControllerFlowGenerationPrompt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAiControllerFlowGenerationPromptWithDefaults() *AiControllerFlowGenerationPrompt {
	this := AiControllerFlowGenerationPrompt{}
	return &this
}

// GetConversationId returns the ConversationId field value
func (o *AiControllerFlowGenerationPrompt) GetConversationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value
// and a boolean to check if the value has been set.
func (o *AiControllerFlowGenerationPrompt) GetConversationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConversationId, true
}

// SetConversationId sets field value
func (o *AiControllerFlowGenerationPrompt) SetConversationId(v string) {
	o.ConversationId = v
}

// GetUserPrompt returns the UserPrompt field value
func (o *AiControllerFlowGenerationPrompt) GetUserPrompt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserPrompt
}

// GetUserPromptOk returns a tuple with the UserPrompt field value
// and a boolean to check if the value has been set.
func (o *AiControllerFlowGenerationPrompt) GetUserPromptOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserPrompt, true
}

// SetUserPrompt sets field value
func (o *AiControllerFlowGenerationPrompt) SetUserPrompt(v string) {
	o.UserPrompt = v
}

// GetYaml returns the Yaml field value if set, zero value otherwise.
func (o *AiControllerFlowGenerationPrompt) GetYaml() string {
	if o == nil || IsNil(o.Yaml) {
		var ret string
		return ret
	}
	return *o.Yaml
}

// GetYamlOk returns a tuple with the Yaml field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiControllerFlowGenerationPrompt) GetYamlOk() (*string, bool) {
	if o == nil || IsNil(o.Yaml) {
		return nil, false
	}
	return o.Yaml, true
}

// HasYaml returns a boolean if a field has been set.
func (o *AiControllerFlowGenerationPrompt) HasYaml() bool {
	if o != nil && !IsNil(o.Yaml) {
		return true
	}

	return false
}

// SetYaml gets a reference to the given string and assigns it to the Yaml field.
func (o *AiControllerFlowGenerationPrompt) SetYaml(v string) {
	o.Yaml = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *AiControllerFlowGenerationPrompt) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiControllerFlowGenerationPrompt) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *AiControllerFlowGenerationPrompt) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *AiControllerFlowGenerationPrompt) SetNamespace(v string) {
	o.Namespace = &v
}

// GetProviderId returns the ProviderId field value if set, zero value otherwise.
func (o *AiControllerFlowGenerationPrompt) GetProviderId() string {
	if o == nil || IsNil(o.ProviderId) {
		var ret string
		return ret
	}
	return *o.ProviderId
}

// GetProviderIdOk returns a tuple with the ProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AiControllerFlowGenerationPrompt) GetProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProviderId) {
		return nil, false
	}
	return o.ProviderId, true
}

// HasProviderId returns a boolean if a field has been set.
func (o *AiControllerFlowGenerationPrompt) HasProviderId() bool {
	if o != nil && !IsNil(o.ProviderId) {
		return true
	}

	return false
}

// SetProviderId gets a reference to the given string and assigns it to the ProviderId field.
func (o *AiControllerFlowGenerationPrompt) SetProviderId(v string) {
	o.ProviderId = &v
}

func (o AiControllerFlowGenerationPrompt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AiControllerFlowGenerationPrompt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["conversationId"] = o.ConversationId
	toSerialize["userPrompt"] = o.UserPrompt
	if !IsNil(o.Yaml) {
		toSerialize["yaml"] = o.Yaml
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.ProviderId) {
		toSerialize["providerId"] = o.ProviderId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AiControllerFlowGenerationPrompt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"conversationId",
		"userPrompt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAiControllerFlowGenerationPrompt := _AiControllerFlowGenerationPrompt{}

	err = json.Unmarshal(data, &varAiControllerFlowGenerationPrompt)

	if err != nil {
		return err
	}

	*o = AiControllerFlowGenerationPrompt(varAiControllerFlowGenerationPrompt)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "conversationId")
		delete(additionalProperties, "userPrompt")
		delete(additionalProperties, "yaml")
		delete(additionalProperties, "namespace")
		delete(additionalProperties, "providerId")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAiControllerFlowGenerationPrompt struct {
	value *AiControllerFlowGenerationPrompt
	isSet bool
}

func (v NullableAiControllerFlowGenerationPrompt) Get() *AiControllerFlowGenerationPrompt {
	return v.value
}

func (v *NullableAiControllerFlowGenerationPrompt) Set(val *AiControllerFlowGenerationPrompt) {
	v.value = val
	v.isSet = true
}

func (v NullableAiControllerFlowGenerationPrompt) IsSet() bool {
	return v.isSet
}

func (v *NullableAiControllerFlowGenerationPrompt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAiControllerFlowGenerationPrompt(val *AiControllerFlowGenerationPrompt) *NullableAiControllerFlowGenerationPrompt {
	return &NullableAiControllerFlowGenerationPrompt{value: val, isSet: true}
}

func (v NullableAiControllerFlowGenerationPrompt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAiControllerFlowGenerationPrompt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


