/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
)

// checks if the SoftDeletableFlowInterface type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SoftDeletableFlowInterface{}

// SoftDeletableFlowInterface struct for SoftDeletableFlowInterface
type SoftDeletableFlowInterface struct {
	Deleted *bool `json:"deleted,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _SoftDeletableFlowInterface SoftDeletableFlowInterface

// NewSoftDeletableFlowInterface instantiates a new SoftDeletableFlowInterface object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSoftDeletableFlowInterface() *SoftDeletableFlowInterface {
	this := SoftDeletableFlowInterface{}
	return &this
}

// NewSoftDeletableFlowInterfaceWithDefaults instantiates a new SoftDeletableFlowInterface object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSoftDeletableFlowInterfaceWithDefaults() *SoftDeletableFlowInterface {
	this := SoftDeletableFlowInterface{}
	return &this
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *SoftDeletableFlowInterface) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoftDeletableFlowInterface) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *SoftDeletableFlowInterface) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *SoftDeletableFlowInterface) SetDeleted(v bool) {
	o.Deleted = &v
}

func (o SoftDeletableFlowInterface) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SoftDeletableFlowInterface) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SoftDeletableFlowInterface) UnmarshalJSON(data []byte) (err error) {
	varSoftDeletableFlowInterface := _SoftDeletableFlowInterface{}

	err = json.Unmarshal(data, &varSoftDeletableFlowInterface)

	if err != nil {
		return err
	}

	*o = SoftDeletableFlowInterface(varSoftDeletableFlowInterface)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "deleted")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSoftDeletableFlowInterface struct {
	value *SoftDeletableFlowInterface
	isSet bool
}

func (v NullableSoftDeletableFlowInterface) Get() *SoftDeletableFlowInterface {
	return v.value
}

func (v *NullableSoftDeletableFlowInterface) Set(val *SoftDeletableFlowInterface) {
	v.value = val
	v.isSet = true
}

func (v NullableSoftDeletableFlowInterface) IsSet() bool {
	return v.isSet
}

func (v *NullableSoftDeletableFlowInterface) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSoftDeletableFlowInterface(val *SoftDeletableFlowInterface) *NullableSoftDeletableFlowInterface {
	return &NullableSoftDeletableFlowInterface{value: val, isSet: true}
}

func (v NullableSoftDeletableFlowInterface) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSoftDeletableFlowInterface) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


