/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

API version: 2.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ApiCreateCredentialRequest - Request to create a new credential. Use 'type' field to specify credential type.
type ApiCreateCredentialRequest struct {
	ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest *ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest
	ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest *ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest
}

// ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequestAsApiCreateCredentialRequest is a convenience function that returns ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest wrapped in ApiCreateCredentialRequest
func ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequestAsApiCreateCredentialRequest(v *ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest) ApiCreateCredentialRequest {
	return ApiCreateCredentialRequest{
		ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest: v,
	}
}

// ApiCreateCredentialRequestApiCreateOAuth2CredentialRequestAsApiCreateCredentialRequest is a convenience function that returns ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest wrapped in ApiCreateCredentialRequest
func ApiCreateCredentialRequestApiCreateOAuth2CredentialRequestAsApiCreateCredentialRequest(v *ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest) ApiCreateCredentialRequest {
	return ApiCreateCredentialRequest{
		ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ApiCreateCredentialRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest
	err = newStrictDecoder(data).Decode(&dst.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest)
	if err == nil {
		jsonApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest, _ := json.Marshal(dst.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest)
		if string(jsonApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest) == "{}" { // empty struct
			dst.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest = nil
		} else {
			if err = validator.Validate(dst.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest); err != nil {
				dst.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest = nil
	}

	// try to unmarshal data into ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest
	err = newStrictDecoder(data).Decode(&dst.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest)
	if err == nil {
		jsonApiCreateCredentialRequestApiCreateOAuth2CredentialRequest, _ := json.Marshal(dst.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest)
		if string(jsonApiCreateCredentialRequestApiCreateOAuth2CredentialRequest) == "{}" { // empty struct
			dst.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest = nil
		} else {
			if err = validator.Validate(dst.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest); err != nil {
				dst.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest = nil
			} else {
				match++
			}
		}
	} else {
		dst.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest = nil
		dst.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ApiCreateCredentialRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ApiCreateCredentialRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ApiCreateCredentialRequest) MarshalJSON() ([]byte, error) {
	if src.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest != nil {
		return json.Marshal(&src.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest)
	}

	if src.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest != nil {
		return json.Marshal(&src.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ApiCreateCredentialRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest != nil {
		return obj.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest
	}

	if obj.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest != nil {
		return obj.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ApiCreateCredentialRequest) GetActualInstanceValue() (interface{}) {
	if obj.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest != nil {
		return *obj.ApiCreateCredentialRequestApiCreateGitHubAppCredentialRequest
	}

	if obj.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest != nil {
		return *obj.ApiCreateCredentialRequestApiCreateOAuth2CredentialRequest
	}

	// all schemas are nil
	return nil
}

type NullableApiCreateCredentialRequest struct {
	value *ApiCreateCredentialRequest
	isSet bool
}

func (v NullableApiCreateCredentialRequest) Get() *ApiCreateCredentialRequest {
	return v.value
}

func (v *NullableApiCreateCredentialRequest) Set(val *ApiCreateCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCreateCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCreateCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCreateCredentialRequest(val *ApiCreateCredentialRequest) *NullableApiCreateCredentialRequest {
	return &NullableApiCreateCredentialRequest{value: val, isSet: true}
}

func (v NullableApiCreateCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCreateCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


