/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

API version: 2.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
)

// checks if the WorkerCredentialControllerApiWorkerList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WorkerCredentialControllerApiWorkerList{}

// WorkerCredentialControllerApiWorkerList struct for WorkerCredentialControllerApiWorkerList
type WorkerCredentialControllerApiWorkerList struct {
	Workers []WorkerCredentialControllerApiWorkerCredential `json:"workers,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _WorkerCredentialControllerApiWorkerList WorkerCredentialControllerApiWorkerList

// NewWorkerCredentialControllerApiWorkerList instantiates a new WorkerCredentialControllerApiWorkerList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWorkerCredentialControllerApiWorkerList() *WorkerCredentialControllerApiWorkerList {
	this := WorkerCredentialControllerApiWorkerList{}
	return &this
}

// NewWorkerCredentialControllerApiWorkerListWithDefaults instantiates a new WorkerCredentialControllerApiWorkerList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWorkerCredentialControllerApiWorkerListWithDefaults() *WorkerCredentialControllerApiWorkerList {
	this := WorkerCredentialControllerApiWorkerList{}
	return &this
}

// GetWorkers returns the Workers field value if set, zero value otherwise.
func (o *WorkerCredentialControllerApiWorkerList) GetWorkers() []WorkerCredentialControllerApiWorkerCredential {
	if o == nil || IsNil(o.Workers) {
		var ret []WorkerCredentialControllerApiWorkerCredential
		return ret
	}
	return o.Workers
}

// GetWorkersOk returns a tuple with the Workers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WorkerCredentialControllerApiWorkerList) GetWorkersOk() ([]WorkerCredentialControllerApiWorkerCredential, bool) {
	if o == nil || IsNil(o.Workers) {
		return nil, false
	}
	return o.Workers, true
}

// HasWorkers returns a boolean if a field has been set.
func (o *WorkerCredentialControllerApiWorkerList) HasWorkers() bool {
	if o != nil && !IsNil(o.Workers) {
		return true
	}

	return false
}

// SetWorkers gets a reference to the given []WorkerCredentialControllerApiWorkerCredential and assigns it to the Workers field.
func (o *WorkerCredentialControllerApiWorkerList) SetWorkers(v []WorkerCredentialControllerApiWorkerCredential) {
	o.Workers = v
}

func (o WorkerCredentialControllerApiWorkerList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WorkerCredentialControllerApiWorkerList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Workers) {
		toSerialize["workers"] = o.Workers
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *WorkerCredentialControllerApiWorkerList) UnmarshalJSON(data []byte) (err error) {
	varWorkerCredentialControllerApiWorkerList := _WorkerCredentialControllerApiWorkerList{}

	err = json.Unmarshal(data, &varWorkerCredentialControllerApiWorkerList)

	if err != nil {
		return err
	}

	*o = WorkerCredentialControllerApiWorkerList(varWorkerCredentialControllerApiWorkerList)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "workers")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableWorkerCredentialControllerApiWorkerList struct {
	value *WorkerCredentialControllerApiWorkerList
	isSet bool
}

func (v NullableWorkerCredentialControllerApiWorkerList) Get() *WorkerCredentialControllerApiWorkerList {
	return v.value
}

func (v *NullableWorkerCredentialControllerApiWorkerList) Set(val *WorkerCredentialControllerApiWorkerList) {
	v.value = val
	v.isSet = true
}

func (v NullableWorkerCredentialControllerApiWorkerList) IsSet() bool {
	return v.isSet
}

func (v *NullableWorkerCredentialControllerApiWorkerList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWorkerCredentialControllerApiWorkerList(val *WorkerCredentialControllerApiWorkerList) *NullableWorkerCredentialControllerApiWorkerList {
	return &NullableWorkerCredentialControllerApiWorkerList{value: val, isSet: true}
}

func (v NullableWorkerCredentialControllerApiWorkerList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWorkerCredentialControllerApiWorkerList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


