/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

API version: 2.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
)

// checks if the PebbleFunction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PebbleFunction{}

// PebbleFunction struct for PebbleFunction
type PebbleFunction struct {
	Name *string `json:"name,omitempty"`
	Arguments []PebbleFunctionArgument `json:"arguments,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PebbleFunction PebbleFunction

// NewPebbleFunction instantiates a new PebbleFunction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPebbleFunction() *PebbleFunction {
	this := PebbleFunction{}
	return &this
}

// NewPebbleFunctionWithDefaults instantiates a new PebbleFunction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPebbleFunctionWithDefaults() *PebbleFunction {
	this := PebbleFunction{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PebbleFunction) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PebbleFunction) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PebbleFunction) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PebbleFunction) SetName(v string) {
	o.Name = &v
}

// GetArguments returns the Arguments field value if set, zero value otherwise.
func (o *PebbleFunction) GetArguments() []PebbleFunctionArgument {
	if o == nil || IsNil(o.Arguments) {
		var ret []PebbleFunctionArgument
		return ret
	}
	return o.Arguments
}

// GetArgumentsOk returns a tuple with the Arguments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PebbleFunction) GetArgumentsOk() ([]PebbleFunctionArgument, bool) {
	if o == nil || IsNil(o.Arguments) {
		return nil, false
	}
	return o.Arguments, true
}

// HasArguments returns a boolean if a field has been set.
func (o *PebbleFunction) HasArguments() bool {
	if o != nil && !IsNil(o.Arguments) {
		return true
	}

	return false
}

// SetArguments gets a reference to the given []PebbleFunctionArgument and assigns it to the Arguments field.
func (o *PebbleFunction) SetArguments(v []PebbleFunctionArgument) {
	o.Arguments = v
}

func (o PebbleFunction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PebbleFunction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Arguments) {
		toSerialize["arguments"] = o.Arguments
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PebbleFunction) UnmarshalJSON(data []byte) (err error) {
	varPebbleFunction := _PebbleFunction{}

	err = json.Unmarshal(data, &varPebbleFunction)

	if err != nil {
		return err
	}

	*o = PebbleFunction(varPebbleFunction)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "name")
		delete(additionalProperties, "arguments")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePebbleFunction struct {
	value *PebbleFunction
	isSet bool
}

func (v NullablePebbleFunction) Get() *PebbleFunction {
	return v.value
}

func (v *NullablePebbleFunction) Set(val *PebbleFunction) {
	v.value = val
	v.isSet = true
}

func (v NullablePebbleFunction) IsSet() bool {
	return v.isSet
}

func (v *NullablePebbleFunction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePebbleFunction(val *PebbleFunction) *NullablePebbleFunction {
	return &NullablePebbleFunction{value: val, isSet: true}
}

func (v NullablePebbleFunction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePebbleFunction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


