/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

API version: 2.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
)

// checks if the OutputControllerTaskOutputInformation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputControllerTaskOutputInformation{}

// OutputControllerTaskOutputInformation struct for OutputControllerTaskOutputInformation
type OutputControllerTaskOutputInformation struct {
	TaskId *string `json:"taskId,omitempty"`
	TaskRunId *string `json:"taskRunId,omitempty"`
	Value *string `json:"value,omitempty"`
	Iteration *int32 `json:"iteration,omitempty"`
	Inline *bool `json:"inline,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _OutputControllerTaskOutputInformation OutputControllerTaskOutputInformation

// NewOutputControllerTaskOutputInformation instantiates a new OutputControllerTaskOutputInformation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputControllerTaskOutputInformation() *OutputControllerTaskOutputInformation {
	this := OutputControllerTaskOutputInformation{}
	return &this
}

// NewOutputControllerTaskOutputInformationWithDefaults instantiates a new OutputControllerTaskOutputInformation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputControllerTaskOutputInformationWithDefaults() *OutputControllerTaskOutputInformation {
	this := OutputControllerTaskOutputInformation{}
	return &this
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *OutputControllerTaskOutputInformation) GetTaskId() string {
	if o == nil || IsNil(o.TaskId) {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputControllerTaskOutputInformation) GetTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *OutputControllerTaskOutputInformation) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *OutputControllerTaskOutputInformation) SetTaskId(v string) {
	o.TaskId = &v
}

// GetTaskRunId returns the TaskRunId field value if set, zero value otherwise.
func (o *OutputControllerTaskOutputInformation) GetTaskRunId() string {
	if o == nil || IsNil(o.TaskRunId) {
		var ret string
		return ret
	}
	return *o.TaskRunId
}

// GetTaskRunIdOk returns a tuple with the TaskRunId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputControllerTaskOutputInformation) GetTaskRunIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskRunId) {
		return nil, false
	}
	return o.TaskRunId, true
}

// HasTaskRunId returns a boolean if a field has been set.
func (o *OutputControllerTaskOutputInformation) HasTaskRunId() bool {
	if o != nil && !IsNil(o.TaskRunId) {
		return true
	}

	return false
}

// SetTaskRunId gets a reference to the given string and assigns it to the TaskRunId field.
func (o *OutputControllerTaskOutputInformation) SetTaskRunId(v string) {
	o.TaskRunId = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *OutputControllerTaskOutputInformation) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputControllerTaskOutputInformation) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *OutputControllerTaskOutputInformation) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *OutputControllerTaskOutputInformation) SetValue(v string) {
	o.Value = &v
}

// GetIteration returns the Iteration field value if set, zero value otherwise.
func (o *OutputControllerTaskOutputInformation) GetIteration() int32 {
	if o == nil || IsNil(o.Iteration) {
		var ret int32
		return ret
	}
	return *o.Iteration
}

// GetIterationOk returns a tuple with the Iteration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputControllerTaskOutputInformation) GetIterationOk() (*int32, bool) {
	if o == nil || IsNil(o.Iteration) {
		return nil, false
	}
	return o.Iteration, true
}

// HasIteration returns a boolean if a field has been set.
func (o *OutputControllerTaskOutputInformation) HasIteration() bool {
	if o != nil && !IsNil(o.Iteration) {
		return true
	}

	return false
}

// SetIteration gets a reference to the given int32 and assigns it to the Iteration field.
func (o *OutputControllerTaskOutputInformation) SetIteration(v int32) {
	o.Iteration = &v
}

// GetInline returns the Inline field value if set, zero value otherwise.
func (o *OutputControllerTaskOutputInformation) GetInline() bool {
	if o == nil || IsNil(o.Inline) {
		var ret bool
		return ret
	}
	return *o.Inline
}

// GetInlineOk returns a tuple with the Inline field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputControllerTaskOutputInformation) GetInlineOk() (*bool, bool) {
	if o == nil || IsNil(o.Inline) {
		return nil, false
	}
	return o.Inline, true
}

// HasInline returns a boolean if a field has been set.
func (o *OutputControllerTaskOutputInformation) HasInline() bool {
	if o != nil && !IsNil(o.Inline) {
		return true
	}

	return false
}

// SetInline gets a reference to the given bool and assigns it to the Inline field.
func (o *OutputControllerTaskOutputInformation) SetInline(v bool) {
	o.Inline = &v
}

func (o OutputControllerTaskOutputInformation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputControllerTaskOutputInformation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TaskId) {
		toSerialize["taskId"] = o.TaskId
	}
	if !IsNil(o.TaskRunId) {
		toSerialize["taskRunId"] = o.TaskRunId
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	if !IsNil(o.Iteration) {
		toSerialize["iteration"] = o.Iteration
	}
	if !IsNil(o.Inline) {
		toSerialize["inline"] = o.Inline
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *OutputControllerTaskOutputInformation) UnmarshalJSON(data []byte) (err error) {
	varOutputControllerTaskOutputInformation := _OutputControllerTaskOutputInformation{}

	err = json.Unmarshal(data, &varOutputControllerTaskOutputInformation)

	if err != nil {
		return err
	}

	*o = OutputControllerTaskOutputInformation(varOutputControllerTaskOutputInformation)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "taskId")
		delete(additionalProperties, "taskRunId")
		delete(additionalProperties, "value")
		delete(additionalProperties, "iteration")
		delete(additionalProperties, "inline")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableOutputControllerTaskOutputInformation struct {
	value *OutputControllerTaskOutputInformation
	isSet bool
}

func (v NullableOutputControllerTaskOutputInformation) Get() *OutputControllerTaskOutputInformation {
	return v.value
}

func (v *NullableOutputControllerTaskOutputInformation) Set(val *OutputControllerTaskOutputInformation) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputControllerTaskOutputInformation) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputControllerTaskOutputInformation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputControllerTaskOutputInformation(val *OutputControllerTaskOutputInformation) *NullableOutputControllerTaskOutputInformation {
	return &NullableOutputControllerTaskOutputInformation{value: val, isSet: true}
}

func (v NullableOutputControllerTaskOutputInformation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputControllerTaskOutputInformation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


