/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

API version: 2.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
	"fmt"
)

// Resource the model 'Resource'
type Resource string

// List of Resource
const (
	RESOURCE_FLOW Resource = "FLOW"
	RESOURCE_EXECUTION Resource = "EXECUTION"
	RESOURCE_TRIGGER Resource = "TRIGGER"
	RESOURCE_NAMESPACE Resource = "NAMESPACE"
	RESOURCE_KVSTORE Resource = "KVSTORE"
	RESOURCE_DASHBOARD Resource = "DASHBOARD"
	RESOURCE_SECRET Resource = "SECRET"
	RESOURCE_CREDENTIAL Resource = "CREDENTIAL"
	RESOURCE_BLUEPRINT Resource = "BLUEPRINT"
	RESOURCE_APP Resource = "APP"
	RESOURCE_AUDITLOG Resource = "AUDITLOG"
	RESOURCE_SYSTEM_SETTINGS Resource = "SYSTEM_SETTINGS"
	RESOURCE_TENANT_SETTINGS Resource = "TENANT_SETTINGS"
	RESOURCE_TESTSUITE Resource = "TESTSUITE"
	RESOURCE_ASSET Resource = "ASSET"
	RESOURCE_USER Resource = "USER"
	RESOURCE_GROUP Resource = "GROUP"
	RESOURCE_ROLE Resource = "ROLE"
	RESOURCE_BINDING Resource = "BINDING"
	RESOURCE_SERVICE_ACCOUNT Resource = "SERVICE_ACCOUNT"
	RESOURCE_INVITATION Resource = "INVITATION"
	RESOURCE_COPILOT Resource = "COPILOT"
	RESOURCE_APP_EXECUTION Resource = "APP_EXECUTION"
	RESOURCE_NAMESPACE_FILE Resource = "NAMESPACE_FILE"
	RESOURCE_TESTSUITE_RUN Resource = "TESTSUITE_RUN"
	RESOURCE_TENANT_ACCESS Resource = "TENANT_ACCESS"
	RESOURCE_SECURITY_INTEGRATION Resource = "SECURITY_INTEGRATION"
	RESOURCE_MCP_SERVER Resource = "MCP_SERVER"
	RESOURCE_KILL_SWITCH Resource = "KILL_SWITCH"
	RESOURCE_TENANT Resource = "TENANT"
	RESOURCE_VERSIONED_PLUGIN Resource = "VERSIONED_PLUGIN"
	RESOURCE_WORKER_GROUP Resource = "WORKER_GROUP"
	RESOURCE_INSTANCE Resource = "INSTANCE"
	RESOURCE_UNKNOWN Resource = "UNKNOWN"
)

// All allowed values of Resource enum
var AllowedResourceEnumValues = []Resource{
	"FLOW",
	"EXECUTION",
	"TRIGGER",
	"NAMESPACE",
	"KVSTORE",
	"DASHBOARD",
	"SECRET",
	"CREDENTIAL",
	"BLUEPRINT",
	"APP",
	"AUDITLOG",
	"SYSTEM_SETTINGS",
	"TENANT_SETTINGS",
	"TESTSUITE",
	"ASSET",
	"USER",
	"GROUP",
	"ROLE",
	"BINDING",
	"SERVICE_ACCOUNT",
	"INVITATION",
	"COPILOT",
	"APP_EXECUTION",
	"NAMESPACE_FILE",
	"TESTSUITE_RUN",
	"TENANT_ACCESS",
	"SECURITY_INTEGRATION",
	"MCP_SERVER",
	"KILL_SWITCH",
	"TENANT",
	"VERSIONED_PLUGIN",
	"WORKER_GROUP",
	"INSTANCE",
	"UNKNOWN",
}

func (v *Resource) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := Resource(value)
	for _, existing := range AllowedResourceEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid Resource", value)
}

// NewResourceFromValue returns a pointer to a valid Resource
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewResourceFromValue(v string) (*Resource, error) {
	ev := Resource(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Resource: valid values are %v", v, AllowedResourceEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Resource) IsValid() bool {
	for _, existing := range AllowedResourceEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Resource value
func (v Resource) Ptr() *Resource {
	return &v
}

type NullableResource struct {
	value *Resource
	isSet bool
}

func (v NullableResource) Get() *Resource {
	return v.value
}

func (v *NullableResource) Set(val *Resource) {
	v.value = val
	v.isSet = true
}

func (v NullableResource) IsSet() bool {
	return v.isSet
}

func (v *NullableResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResource(val *Resource) *NullableResource {
	return &NullableResource{value: val, isSet: true}
}

func (v NullableResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

