/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

API version: 2.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
)

// checks if the ExpressionContext type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ExpressionContext{}

// ExpressionContext struct for ExpressionContext
type ExpressionContext struct {
	Categories *ExpressionContextCategories `json:"categories,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ExpressionContext ExpressionContext

// NewExpressionContext instantiates a new ExpressionContext object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExpressionContext() *ExpressionContext {
	this := ExpressionContext{}
	return &this
}

// NewExpressionContextWithDefaults instantiates a new ExpressionContext object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExpressionContextWithDefaults() *ExpressionContext {
	this := ExpressionContext{}
	return &this
}

// GetCategories returns the Categories field value if set, zero value otherwise.
func (o *ExpressionContext) GetCategories() ExpressionContextCategories {
	if o == nil || IsNil(o.Categories) {
		var ret ExpressionContextCategories
		return ret
	}
	return *o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExpressionContext) GetCategoriesOk() (*ExpressionContextCategories, bool) {
	if o == nil || IsNil(o.Categories) {
		return nil, false
	}
	return o.Categories, true
}

// HasCategories returns a boolean if a field has been set.
func (o *ExpressionContext) HasCategories() bool {
	if o != nil && !IsNil(o.Categories) {
		return true
	}

	return false
}

// SetCategories gets a reference to the given ExpressionContextCategories and assigns it to the Categories field.
func (o *ExpressionContext) SetCategories(v ExpressionContextCategories) {
	o.Categories = &v
}

func (o ExpressionContext) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ExpressionContext) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Categories) {
		toSerialize["categories"] = o.Categories
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ExpressionContext) UnmarshalJSON(data []byte) (err error) {
	varExpressionContext := _ExpressionContext{}

	err = json.Unmarshal(data, &varExpressionContext)

	if err != nil {
		return err
	}

	*o = ExpressionContext(varExpressionContext)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "categories")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableExpressionContext struct {
	value *ExpressionContext
	isSet bool
}

func (v NullableExpressionContext) Get() *ExpressionContext {
	return v.value
}

func (v *NullableExpressionContext) Set(val *ExpressionContext) {
	v.value = val
	v.isSet = true
}

func (v NullableExpressionContext) IsSet() bool {
	return v.isSet
}

func (v *NullableExpressionContext) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExpressionContext(val *ExpressionContext) *NullableExpressionContext {
	return &NullableExpressionContext{value: val, isSet: true}
}

func (v NullableExpressionContext) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExpressionContext) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


