/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

API version: 2.0.0-SNAPSHOT
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
)

// checks if the ApiInheritedCredentialsResponseInheritedCredentialLevel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiInheritedCredentialsResponseInheritedCredentialLevel{}

// ApiInheritedCredentialsResponseInheritedCredentialLevel struct for ApiInheritedCredentialsResponseInheritedCredentialLevel
type ApiInheritedCredentialsResponseInheritedCredentialLevel struct {
	// The namespace from which credentials are inherited, or 'tenant' for tenant-level
	Namespace *string `json:"namespace,omitempty"`
	// Credentials available at this level
	Credentials []ApiInheritedCredentialsResponseInheritedCredential `json:"credentials,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApiInheritedCredentialsResponseInheritedCredentialLevel ApiInheritedCredentialsResponseInheritedCredentialLevel

// NewApiInheritedCredentialsResponseInheritedCredentialLevel instantiates a new ApiInheritedCredentialsResponseInheritedCredentialLevel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiInheritedCredentialsResponseInheritedCredentialLevel() *ApiInheritedCredentialsResponseInheritedCredentialLevel {
	this := ApiInheritedCredentialsResponseInheritedCredentialLevel{}
	return &this
}

// NewApiInheritedCredentialsResponseInheritedCredentialLevelWithDefaults instantiates a new ApiInheritedCredentialsResponseInheritedCredentialLevel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiInheritedCredentialsResponseInheritedCredentialLevelWithDefaults() *ApiInheritedCredentialsResponseInheritedCredentialLevel {
	this := ApiInheritedCredentialsResponseInheritedCredentialLevel{}
	return &this
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *ApiInheritedCredentialsResponseInheritedCredentialLevel) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInheritedCredentialsResponseInheritedCredentialLevel) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *ApiInheritedCredentialsResponseInheritedCredentialLevel) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *ApiInheritedCredentialsResponseInheritedCredentialLevel) SetNamespace(v string) {
	o.Namespace = &v
}

// GetCredentials returns the Credentials field value if set, zero value otherwise.
func (o *ApiInheritedCredentialsResponseInheritedCredentialLevel) GetCredentials() []ApiInheritedCredentialsResponseInheritedCredential {
	if o == nil || IsNil(o.Credentials) {
		var ret []ApiInheritedCredentialsResponseInheritedCredential
		return ret
	}
	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiInheritedCredentialsResponseInheritedCredentialLevel) GetCredentialsOk() ([]ApiInheritedCredentialsResponseInheritedCredential, bool) {
	if o == nil || IsNil(o.Credentials) {
		return nil, false
	}
	return o.Credentials, true
}

// HasCredentials returns a boolean if a field has been set.
func (o *ApiInheritedCredentialsResponseInheritedCredentialLevel) HasCredentials() bool {
	if o != nil && !IsNil(o.Credentials) {
		return true
	}

	return false
}

// SetCredentials gets a reference to the given []ApiInheritedCredentialsResponseInheritedCredential and assigns it to the Credentials field.
func (o *ApiInheritedCredentialsResponseInheritedCredentialLevel) SetCredentials(v []ApiInheritedCredentialsResponseInheritedCredential) {
	o.Credentials = v
}

func (o ApiInheritedCredentialsResponseInheritedCredentialLevel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiInheritedCredentialsResponseInheritedCredentialLevel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	if !IsNil(o.Credentials) {
		toSerialize["credentials"] = o.Credentials
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApiInheritedCredentialsResponseInheritedCredentialLevel) UnmarshalJSON(data []byte) (err error) {
	varApiInheritedCredentialsResponseInheritedCredentialLevel := _ApiInheritedCredentialsResponseInheritedCredentialLevel{}

	err = json.Unmarshal(data, &varApiInheritedCredentialsResponseInheritedCredentialLevel)

	if err != nil {
		return err
	}

	*o = ApiInheritedCredentialsResponseInheritedCredentialLevel(varApiInheritedCredentialsResponseInheritedCredentialLevel)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "namespace")
		delete(additionalProperties, "credentials")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApiInheritedCredentialsResponseInheritedCredentialLevel struct {
	value *ApiInheritedCredentialsResponseInheritedCredentialLevel
	isSet bool
}

func (v NullableApiInheritedCredentialsResponseInheritedCredentialLevel) Get() *ApiInheritedCredentialsResponseInheritedCredentialLevel {
	return v.value
}

func (v *NullableApiInheritedCredentialsResponseInheritedCredentialLevel) Set(val *ApiInheritedCredentialsResponseInheritedCredentialLevel) {
	v.value = val
	v.isSet = true
}

func (v NullableApiInheritedCredentialsResponseInheritedCredentialLevel) IsSet() bool {
	return v.isSet
}

func (v *NullableApiInheritedCredentialsResponseInheritedCredentialLevel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiInheritedCredentialsResponseInheritedCredentialLevel(val *ApiInheritedCredentialsResponseInheritedCredentialLevel) *NullableApiInheritedCredentialsResponseInheritedCredentialLevel {
	return &NullableApiInheritedCredentialsResponseInheritedCredentialLevel{value: val, isSet: true}
}

func (v NullableApiInheritedCredentialsResponseInheritedCredentialLevel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiInheritedCredentialsResponseInheritedCredentialLevel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


