/*
Kestra EE

All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package kestra_api_client

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// UpdateFlowsInNamespaceOverrideParameter - struct for UpdateFlowsInNamespaceOverrideParameter
type UpdateFlowsInNamespaceOverrideParameter struct {
	Bool *bool
}

// boolAsUpdateFlowsInNamespaceOverrideParameter is a convenience function that returns bool wrapped in UpdateFlowsInNamespaceOverrideParameter
func BoolAsUpdateFlowsInNamespaceOverrideParameter(v *bool) UpdateFlowsInNamespaceOverrideParameter {
	return UpdateFlowsInNamespaceOverrideParameter{
		Bool: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *UpdateFlowsInNamespaceOverrideParameter) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Bool
	err = newStrictDecoder(data).Decode(&dst.Bool)
	if err == nil {
		jsonBool, _ := json.Marshal(dst.Bool)
		if string(jsonBool) == "{}" { // empty struct
			dst.Bool = nil
		} else {
			if err = validator.Validate(dst.Bool); err != nil {
				dst.Bool = nil
			} else {
				match++
			}
		}
	} else {
		dst.Bool = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Bool = nil

		return fmt.Errorf("data matches more than one schema in oneOf(UpdateFlowsInNamespaceOverrideParameter)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(UpdateFlowsInNamespaceOverrideParameter)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src UpdateFlowsInNamespaceOverrideParameter) MarshalJSON() ([]byte, error) {
	if src.Bool != nil {
		return json.Marshal(&src.Bool)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *UpdateFlowsInNamespaceOverrideParameter) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Bool != nil {
		return obj.Bool
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj UpdateFlowsInNamespaceOverrideParameter) GetActualInstanceValue() (interface{}) {
	if obj.Bool != nil {
		return *obj.Bool
	}

	// all schemas are nil
	return nil
}

type NullableUpdateFlowsInNamespaceOverrideParameter struct {
	value *UpdateFlowsInNamespaceOverrideParameter
	isSet bool
}

func (v NullableUpdateFlowsInNamespaceOverrideParameter) Get() *UpdateFlowsInNamespaceOverrideParameter {
	return v.value
}

func (v *NullableUpdateFlowsInNamespaceOverrideParameter) Set(val *UpdateFlowsInNamespaceOverrideParameter) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateFlowsInNamespaceOverrideParameter) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateFlowsInNamespaceOverrideParameter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateFlowsInNamespaceOverrideParameter(val *UpdateFlowsInNamespaceOverrideParameter) *NullableUpdateFlowsInNamespaceOverrideParameter {
	return &NullableUpdateFlowsInNamespaceOverrideParameter{value: val, isSet: true}
}

func (v NullableUpdateFlowsInNamespaceOverrideParameter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateFlowsInNamespaceOverrideParameter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


