/**
 * Kestra EE
 * All API operations allow an optional tenant identifier in the HTTP path, if you don't use multi-tenancy you must omit the tenant identifier.<br/> This means that, for example, when trying to access the Flows API, instead of using <code>/api/v1/{tenant}/flows</code> you must use <code>/api/v1/flows</code>.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Action from '../model/Action';
import ApiUser from '../model/ApiUser';
import MiscControllerBasicAuthCredentials from '../model/MiscControllerBasicAuthCredentials';
import MiscControllerEEConfiguration from '../model/MiscControllerEEConfiguration';
import MiscControllerLicenseInfo from '../model/MiscControllerLicenseInfo';
import Permission from '../model/Permission';
import SetupConfiguration from '../model/SetupConfiguration';
import SetupConfigurationSetupData from '../model/SetupConfigurationSetupData';
import Usage from '../model/Usage';
import UsageEE from '../model/UsageEE';

/**
* Misc service.
* @module api/MiscApi
* @version v1
*/
export default class MiscApi {

    /**
    * Constructs a new MiscApi. 
    * @alias module:api/MiscApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Create basic auth for the current instance
     * @param {module:model/MiscControllerBasicAuthCredentials} miscControllerBasicAuthCredentials 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing HTTP response
     */
    createBasicAuthWithHttpInfo(miscControllerBasicAuthCredentials) {
      let postBody = miscControllerBasicAuthCredentials;
      // verify the required parameter 'miscControllerBasicAuthCredentials' is set
      if (miscControllerBasicAuthCredentials === undefined || miscControllerBasicAuthCredentials === null) {
        throw new Error("Missing the required parameter 'miscControllerBasicAuthCredentials' when calling createBasicAuth");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/main/basicAuth', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create basic auth for the current instance
     * @param {module:model/MiscControllerBasicAuthCredentials} miscControllerBasicAuthCredentials 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}
     */
    createBasicAuth(miscControllerBasicAuthCredentials) {
      return this.createBasicAuthWithHttpInfo(miscControllerBasicAuthCredentials)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get current configurations
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/MiscControllerEEConfiguration} and HTTP response
     */
    getConfigurationWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MiscControllerEEConfiguration;
      return this.apiClient.callApi(
        '/api/v1/configs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get current configurations
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/MiscControllerEEConfiguration}
     */
    getConfiguration() {
      return this.getConfigurationWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get instance usage information
     * @param {String} tenant 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/Usage} and HTTP response
     */
    getUsagesWithHttpInfo(tenant) {
      let postBody = null;
      // verify the required parameter 'tenant' is set
      if (tenant === undefined || tenant === null) {
        throw new Error("Missing the required parameter 'tenant' when calling getUsages");
      }

      let pathParams = {
        'tenant': tenant
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Usage;
      return this.apiClient.callApi(
        '/api/v1/{tenant}/usages/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get instance usage information
     * @param {String} tenant 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/Usage}
     */
    getUsages(tenant) {
      return this.getUsagesWithHttpInfo(tenant)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get current license information
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/MiscControllerLicenseInfo} and HTTP response
     */
    licenseInfoWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = MiscControllerLicenseInfo;
      return this.apiClient.callApi(
        '/api/v1/license-info', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get current license information
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/MiscControllerLicenseInfo}
     */
    licenseInfo() {
      return this.licenseInfoWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get list of actions
     * @param {String} tenant 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Action>} and HTTP response
     */
    listActionsWithHttpInfo(tenant) {
      let postBody = null;
      // verify the required parameter 'tenant' is set
      if (tenant === undefined || tenant === null) {
        throw new Error("Missing the required parameter 'tenant' when calling listActions");
      }

      let pathParams = {
        'tenant': tenant
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Action];
      return this.apiClient.callApi(
        '/api/v1/{tenant}/acls/actions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get list of actions
     * @param {String} tenant 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Action>}
     */
    listActions(tenant) {
      return this.listActionsWithHttpInfo(tenant)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get list of permissions
     * @param {String} tenant 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Array.<module:model/Permission>} and HTTP response
     */
    listPermissionsWithHttpInfo(tenant) {
      let postBody = null;
      // verify the required parameter 'tenant' is set
      if (tenant === undefined || tenant === null) {
        throw new Error("Missing the required parameter 'tenant' when calling listPermissions");
      }

      let pathParams = {
        'tenant': tenant
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Permission];
      return this.apiClient.callApi(
        '/api/v1/{tenant}/acls/permissions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get list of permissions
     * @param {String} tenant 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Array.<module:model/Permission>}
     */
    listPermissions(tenant) {
      return this.listPermissionsWithHttpInfo(tenant)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Currently running configuration
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SetupConfiguration} and HTTP response
     */
    setupConfigurationWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = SetupConfiguration;
      return this.apiClient.callApi(
        '/api/v1/setup', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Currently running configuration
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SetupConfiguration}
     */
    setupConfiguration() {
      return this.setupConfigurationWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Create the first user
     * @param {module:model/SetupConfigurationSetupData} setupConfigurationSetupData 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ApiUser} and HTTP response
     */
    setupKestraWithHttpInfo(setupConfigurationSetupData) {
      let postBody = setupConfigurationSetupData;
      // verify the required parameter 'setupConfigurationSetupData' is set
      if (setupConfigurationSetupData === undefined || setupConfigurationSetupData === null) {
        throw new Error("Missing the required parameter 'setupConfigurationSetupData' when calling setupKestra");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'bearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ApiUser;
      return this.apiClient.callApi(
        '/api/v1/setup', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Create the first user
     * @param {module:model/SetupConfigurationSetupData} setupConfigurationSetupData 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ApiUser}
     */
    setupKestra(setupConfigurationSetupData) {
      return this.setupKestraWithHttpInfo(setupConfigurationSetupData)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Get instance usage information for the current tenant
     * @param {String} tenant 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/UsageEE} and HTTP response
     */
    tenantUsageWithHttpInfo(tenant) {
      let postBody = null;
      // verify the required parameter 'tenant' is set
      if (tenant === undefined || tenant === null) {
        throw new Error("Missing the required parameter 'tenant' when calling tenantUsage");
      }

      let pathParams = {
        'tenant': tenant
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['basicAuth', 'bearerAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = UsageEE;
      return this.apiClient.callApi(
        '/api/v1/{tenant}/usages', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get instance usage information for the current tenant
     * @param {String} tenant 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/UsageEE}
     */
    tenantUsage(tenant) {
      return this.tenantUsageWithHttpInfo(tenant)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
