generatorName: go
inputSpec: /local/kestra-ee.yml
outputDir: /local/go-sdk

globalProperties:
  apiTests: true
  modelTests: false
  apiDocs: true
  modelDocs: true


additionalProperties:
  packageName: kestra_api_client
  projectName: kestra_api
  enumClassPrefix: true
  disallowAdditionalPropertiesIfNotPresent: false

gitUserId: kestra-io
gitRepoId: client-sdk/go-sdk

hideGenerationTimestamp: true

typeMappings:
  PropertyDuration: string
  PropertyString: string
  PropertyBoolean: string
  PropertyDouble: string
  PropertyListString: string
  PropertyObject: string

openapiNormalizer:
  FILTER: 'tag:Executions|Flows|Namespaces|Triggers|Users|Groups|KV|Roles|ServiceAccount'