generatorName: javascript
inputSpec: /local/kestra-ee.yml
outputDir: /local/javascript-sdk

globalProperties:
  apiTests: false
  modelTests: false

hideGenerationTimestamp: true

additionalProperties:
  packageName: "@kestra-io/kestra-sdk"
  projectName: "@kestra-io/kestra-sdk"
  disallowAdditionalPropertiesIfNotPresent: false
