generatorName: java
inputSpec: /local/kestra-ee.yml
outputDir: /local/java-sdk

globalProperties:
  apiTests: false
  modelTests: false

additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: false

library: apache-httpclient
invokerPackage: io.kestra.sdk.internal
modelPackage: io.kestra.sdk.model
apiPackage: io.kestra.sdk.api
groupId: io.kestra
artifactId: kestra-api-client

hideGenerationTimestamp: true
supportUrlQuery: false

typeMappings:
  PropertyDuration: String
  PropertyString: String
  PropertyBoolean: String
  PropertyDouble: String
  PropertyListString: String
  PropertyObject: String
