generatorName: javascript
inputSpec: /local/kestra-ee.yml
outputDir: /local/javascript-sdk

globalProperties:
  apiTests: true
  modelTests: false
  apiDocs: true
  modelDocs: true

hideGenerationTimestamp: true

additionalProperties:
  packageName: "@kestra-io/kestra-sdk"
  projectName: "@kestra-io/kestra-sdk"
  disallowAdditionalPropertiesIfNotPresent: false

openapiNormalizer:
  FILTER: 'tag:Executions|Flows|Namespaces|Triggers|Users|Groups|KV|Roles|ServiceAccount'
