generatorName: java
inputSpec: /local/kestra-ee.yml
outputDir: /local/java-sdk

globalProperties:
  apiTests: true
  modelTests: false
  apiDocs: true
  modelDocs: true

additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: false

library: apache-httpclient
invokerPackage: io.kestra.sdk.internal
modelPackage: io.kestra.sdk.model
apiPackage: io.kestra.sdk.api
groupId: io.kestra
artifactId: kestra-api-client

hideGenerationTimestamp: true
supportUrlQuery: false

typeMappings:
  PropertyDuration: String
  PropertyString: String
  PropertyBoolean: String
  PropertyDouble: String
  PropertyListString: String
  PropertyObject: String

openapiNormalizer:
  FILTER: 'tag:Executions|Flows|Namespaces|Triggers|Users|Groups|KV|Roles|ServiceAccount'