generatorName: python
inputSpec: /local/kestra-ee.yml
outputDir: /local/python-sdk

globalProperties:
  apiTests: false
  modelTests: false

additionalProperties:
  packageName: kestrapy
  projectName: "@kestra-io/kestrapy"
  packageUrl: "kestra.io"
  packageAuthorEmail: "contact@kestra.io"
  disallowAdditionalPropertiesIfNotPresent: false
  customEmail: "contact@kestra.io"
  customAuthor: "Kestra.io"
  customDescription: "Kestra Python SDK"
