generatorName: python
inputSpec: /local/kestra-ee.yml
outputDir: /local/python-sdk

globalProperties:
  apiTests: false
  modelTests: false

additionalProperties:
  packageName: kestrapy
  projectName: kestrapy
  disallowAdditionalPropertiesIfNotPresent: false
