generatorName: python
inputSpec: /local/kestra-ee.yml
outputDir: /local/python-sdk

globalProperties:
  apiTests: false
  modelTests: false

hideGenerationTimestamp: true

additionalProperties:
  packageName: kestra_api_client
  projectName: "@kestra-io/kestra_api_client"
  packageAuthorEmail: "contact@kestra.io"
  disallowAdditionalPropertiesIfNotPresent: false
  customEmail: "contact@kestra.io"
  customAuthor: "Kestra.io"
  customDescription: "Kestra Python SDK"
