# coding: utf-8

"""
    Kestra EE

    All API operations, except for Instance-owner-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Instance-owner-only are not tenant-scoped.

    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import regex as re
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from kestrapy.models.connection_mode import ConnectionMode
from typing import Optional, Set
from typing_extensions import Self

class ApiCreatePromotionTargetRequest(BaseModel):
    """
    Request to create a new PromotionTarget.
    """ # noqa: E501
    name: Annotated[str, Field(min_length=1, strict=True)] = Field(description="The promotion target name", json_schema_extra={"examples": ["production"]})
    description: Optional[StrictStr] = Field(default=None, description="The promotion target description")
    disabled: Optional[StrictBool] = Field(default=None, description="Whether the target is disabled")
    url: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Base URL of the remote Kestra instance", json_schema_extra={"examples": ["https://prod.kestra.company.com"]})
    target_tenant: Annotated[str, Field(min_length=1, strict=True)] = Field(description="The tenant on the target instance", alias="targetTenant")
    connection_mode: ConnectionMode = Field(description="Connection mode (SERVER or CLIENT)", alias="connectionMode")
    api_token: Optional[StrictStr] = Field(default=None, description="Service-account API token used by the backend (SERVER mode only, encrypted at rest, never returned; CLIENT-mode targets must not carry one)", alias="apiToken")
    gate: Optional[StrictBool] = Field(default=None, description="Whether promotions to this target require confirmation")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["name", "description", "disabled", "url", "targetTenant", "connectionMode", "apiToken", "gate"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiCreatePromotionTargetRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiCreatePromotionTargetRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "disabled": obj.get("disabled"),
            "url": obj.get("url"),
            "targetTenant": obj.get("targetTenant"),
            "connectionMode": obj.get("connectionMode"),
            "apiToken": obj.get("apiToken"),
            "gate": obj.get("gate")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


