/*
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AssetsControllerApiAssetUsage
 */
@JsonPropertyOrder({
  AssetsControllerApiAssetUsage.JSON_PROPERTY_ASSET_ID,
  AssetsControllerApiAssetUsage.JSON_PROPERTY_NAMESPACE,
  AssetsControllerApiAssetUsage.JSON_PROPERTY_FLOW_ID,
  AssetsControllerApiAssetUsage.JSON_PROPERTY_FLOW_REVISION,
  AssetsControllerApiAssetUsage.JSON_PROPERTY_EXECUTION_ID,
  AssetsControllerApiAssetUsage.JSON_PROPERTY_TASK_ID,
  AssetsControllerApiAssetUsage.JSON_PROPERTY_TASK_RUN_ID,
  AssetsControllerApiAssetUsage.JSON_PROPERTY_CREATED
})
@JsonTypeName("AssetsController.ApiAssetUsage")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class AssetsControllerApiAssetUsage {
  public static final String JSON_PROPERTY_ASSET_ID = "assetId";
  @jakarta.annotation.Nullable  private String assetId;

  public static final String JSON_PROPERTY_NAMESPACE = "namespace";
  @jakarta.annotation.Nullable  private String namespace;

  public static final String JSON_PROPERTY_FLOW_ID = "flowId";
  @jakarta.annotation.Nullable  private String flowId;

  public static final String JSON_PROPERTY_FLOW_REVISION = "flowRevision";
  @jakarta.annotation.Nullable  private Integer flowRevision;

  public static final String JSON_PROPERTY_EXECUTION_ID = "executionId";
  @jakarta.annotation.Nullable  private String executionId;

  public static final String JSON_PROPERTY_TASK_ID = "taskId";
  @jakarta.annotation.Nullable  private String taskId;

  public static final String JSON_PROPERTY_TASK_RUN_ID = "taskRunId";
  @jakarta.annotation.Nullable  private String taskRunId;

  public static final String JSON_PROPERTY_CREATED = "created";
  @jakarta.annotation.Nullable  private OffsetDateTime created;

  public AssetsControllerApiAssetUsage() {
  }

  public AssetsControllerApiAssetUsage assetId(@jakarta.annotation.Nullable String assetId) {
    
    this.assetId = assetId;
    return this;
  }

  /**
   * Get assetId
   * @return assetId
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_ASSET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAssetId() {
    return assetId;
  }


  @JsonProperty(JSON_PROPERTY_ASSET_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssetId(@jakarta.annotation.Nullable String assetId) {
    this.assetId = assetId;
  }

  public AssetsControllerApiAssetUsage namespace(@jakarta.annotation.Nullable String namespace) {
    
    this.namespace = namespace;
    return this;
  }

  /**
   * Get namespace
   * @return namespace
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNamespace() {
    return namespace;
  }


  @JsonProperty(JSON_PROPERTY_NAMESPACE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNamespace(@jakarta.annotation.Nullable String namespace) {
    this.namespace = namespace;
  }

  public AssetsControllerApiAssetUsage flowId(@jakarta.annotation.Nullable String flowId) {
    
    this.flowId = flowId;
    return this;
  }

  /**
   * Get flowId
   * @return flowId
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_FLOW_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFlowId() {
    return flowId;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowId(@jakarta.annotation.Nullable String flowId) {
    this.flowId = flowId;
  }

  public AssetsControllerApiAssetUsage flowRevision(@jakarta.annotation.Nullable Integer flowRevision) {
    
    this.flowRevision = flowRevision;
    return this;
  }

  /**
   * Get flowRevision
   * @return flowRevision
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_FLOW_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getFlowRevision() {
    return flowRevision;
  }


  @JsonProperty(JSON_PROPERTY_FLOW_REVISION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFlowRevision(@jakarta.annotation.Nullable Integer flowRevision) {
    this.flowRevision = flowRevision;
  }

  public AssetsControllerApiAssetUsage executionId(@jakarta.annotation.Nullable String executionId) {
    
    this.executionId = executionId;
    return this;
  }

  /**
   * Get executionId
   * @return executionId
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_EXECUTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExecutionId() {
    return executionId;
  }


  @JsonProperty(JSON_PROPERTY_EXECUTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExecutionId(@jakarta.annotation.Nullable String executionId) {
    this.executionId = executionId;
  }

  public AssetsControllerApiAssetUsage taskId(@jakarta.annotation.Nullable String taskId) {
    
    this.taskId = taskId;
    return this;
  }

  /**
   * Get taskId
   * @return taskId
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_TASK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTaskId() {
    return taskId;
  }


  @JsonProperty(JSON_PROPERTY_TASK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaskId(@jakarta.annotation.Nullable String taskId) {
    this.taskId = taskId;
  }

  public AssetsControllerApiAssetUsage taskRunId(@jakarta.annotation.Nullable String taskRunId) {
    
    this.taskRunId = taskRunId;
    return this;
  }

  /**
   * Get taskRunId
   * @return taskRunId
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_TASK_RUN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTaskRunId() {
    return taskRunId;
  }


  @JsonProperty(JSON_PROPERTY_TASK_RUN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaskRunId(@jakarta.annotation.Nullable String taskRunId) {
    this.taskRunId = taskRunId;
  }

  public AssetsControllerApiAssetUsage created(@jakarta.annotation.Nullable OffsetDateTime created) {
    
    this.created = created;
    return this;
  }

  /**
   * Get created
   * @return created
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getCreated() {
    return created;
  }


  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreated(@jakarta.annotation.Nullable OffsetDateTime created) {
    this.created = created;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetsControllerApiAssetUsage assetsControllerApiAssetUsage = (AssetsControllerApiAssetUsage) o;
    return Objects.equals(this.assetId, assetsControllerApiAssetUsage.assetId) &&
        Objects.equals(this.namespace, assetsControllerApiAssetUsage.namespace) &&
        Objects.equals(this.flowId, assetsControllerApiAssetUsage.flowId) &&
        Objects.equals(this.flowRevision, assetsControllerApiAssetUsage.flowRevision) &&
        Objects.equals(this.executionId, assetsControllerApiAssetUsage.executionId) &&
        Objects.equals(this.taskId, assetsControllerApiAssetUsage.taskId) &&
        Objects.equals(this.taskRunId, assetsControllerApiAssetUsage.taskRunId) &&
        Objects.equals(this.created, assetsControllerApiAssetUsage.created);
  }

  @Override
  public int hashCode() {
    return Objects.hash(assetId, namespace, flowId, flowRevision, executionId, taskId, taskRunId, created);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetsControllerApiAssetUsage {\n");
    sb.append("    assetId: ").append(toIndentedString(assetId)).append("\n");
    sb.append("    namespace: ").append(toIndentedString(namespace)).append("\n");
    sb.append("    flowId: ").append(toIndentedString(flowId)).append("\n");
    sb.append("    flowRevision: ").append(toIndentedString(flowRevision)).append("\n");
    sb.append("    executionId: ").append(toIndentedString(executionId)).append("\n");
    sb.append("    taskId: ").append(toIndentedString(taskId)).append("\n");
    sb.append("    taskRunId: ").append(toIndentedString(taskRunId)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

