/*
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.sdk.model.CheckBehavior;
import io.kestra.sdk.model.CheckStyle;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Check
 */
@JsonPropertyOrder({
  Check.JSON_PROPERTY_CONDITION,
  Check.JSON_PROPERTY_MESSAGE,
  Check.JSON_PROPERTY_STYLE,
  Check.JSON_PROPERTY_BEHAVIOR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.18.0")
public class Check {
  public static final String JSON_PROPERTY_CONDITION = "condition";
  @jakarta.annotation.Nonnull  private String condition;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nonnull  private String message;

  public static final String JSON_PROPERTY_STYLE = "style";
  @jakarta.annotation.Nullable  private CheckStyle style;

  public static final String JSON_PROPERTY_BEHAVIOR = "behavior";
  @jakarta.annotation.Nullable  private CheckBehavior behavior;

  public Check() {
  }

  public Check condition(@jakarta.annotation.Nonnull String condition) {
    
    this.condition = condition;
    return this;
  }

  /**
   * Get condition
   * @return condition
   */
  @jakarta.annotation.Nonnull  @JsonProperty(JSON_PROPERTY_CONDITION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCondition() {
    return condition;
  }


  @JsonProperty(JSON_PROPERTY_CONDITION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCondition(@jakarta.annotation.Nonnull String condition) {
    this.condition = condition;
  }

  public Check message(@jakarta.annotation.Nonnull String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nonnull  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMessage(@jakarta.annotation.Nonnull String message) {
    this.message = message;
  }

  public Check style(@jakarta.annotation.Nullable CheckStyle style) {
    
    this.style = style;
    return this;
  }

  /**
   * Get style
   * @return style
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CheckStyle getStyle() {
    return style;
  }


  @JsonProperty(JSON_PROPERTY_STYLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStyle(@jakarta.annotation.Nullable CheckStyle style) {
    this.style = style;
  }

  public Check behavior(@jakarta.annotation.Nullable CheckBehavior behavior) {
    
    this.behavior = behavior;
    return this;
  }

  /**
   * Get behavior
   * @return behavior
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_BEHAVIOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CheckBehavior getBehavior() {
    return behavior;
  }


  @JsonProperty(JSON_PROPERTY_BEHAVIOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBehavior(@jakarta.annotation.Nullable CheckBehavior behavior) {
    this.behavior = behavior;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Check check = (Check) o;
    return Objects.equals(this.condition, check.condition) &&
        Objects.equals(this.message, check.message) &&
        Objects.equals(this.style, check.style) &&
        Objects.equals(this.behavior, check.behavior);
  }

  @Override
  public int hashCode() {
    return Objects.hash(condition, message, style, behavior);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Check {\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("    behavior: ").append(toIndentedString(behavior)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

