/*
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.sdk.model.PluginUiModuleWithGroup;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PluginUiManifest
 */
@JsonPropertyOrder({
  PluginUiManifest.JSON_PROPERTY_MANIFEST
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class PluginUiManifest {
  public static final String JSON_PROPERTY_MANIFEST = "manifest";
  @jakarta.annotation.Nullable  private Map<String, List<PluginUiModuleWithGroup>> manifest = new HashMap<>();

  public PluginUiManifest() {
  }

  public PluginUiManifest manifest(@jakarta.annotation.Nullable Map<String, List<PluginUiModuleWithGroup>> manifest) {
    
    this.manifest = manifest;
    return this;
  }

  public PluginUiManifest putManifestItem(String key, List<PluginUiModuleWithGroup> manifestItem) {
    if (this.manifest == null) {
      this.manifest = new HashMap<>();
    }
    this.manifest.put(key, manifestItem);
    return this;
  }

  /**
   * Get manifest
   * @return manifest
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_MANIFEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Map<String, List<PluginUiModuleWithGroup>> getManifest() {
    return manifest;
  }


  @JsonProperty(JSON_PROPERTY_MANIFEST)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setManifest(@jakarta.annotation.Nullable Map<String, List<PluginUiModuleWithGroup>> manifest) {
    this.manifest = manifest;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PluginUiManifest pluginUiManifest = (PluginUiManifest) o;
    return Objects.equals(this.manifest, pluginUiManifest.manifest);
  }

  @Override
  public int hashCode() {
    return Objects.hash(manifest);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PluginUiManifest {\n");
    sb.append("    manifest: ").append(toIndentedString(manifest)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

