/*
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SLA targets configured on a Case or CaseTemplate. acknowledgement and resolution are ISO-8601 durations (e.g. PT1H).
 */
@JsonPropertyOrder({
  SlaConfig.JSON_PROPERTY_ACKNOWLEDGEMENT,
  SlaConfig.JSON_PROPERTY_RESOLUTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SlaConfig {
  public static final String JSON_PROPERTY_ACKNOWLEDGEMENT = "acknowledgement";
  @jakarta.annotation.Nullable  private String acknowledgement;

  public static final String JSON_PROPERTY_RESOLUTION = "resolution";
  @jakarta.annotation.Nullable  private String resolution;

  public SlaConfig() {
  }

  public SlaConfig acknowledgement(@jakarta.annotation.Nullable String acknowledgement) {

    this.acknowledgement = acknowledgement;
    return this;
  }

  /**
   * Time to acknowledge, counted from case creation, as an ISO-8601 duration (e.g. PT1H).
   * @return acknowledgement
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_ACKNOWLEDGEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAcknowledgement() {
    return acknowledgement;
  }


  @JsonProperty(JSON_PROPERTY_ACKNOWLEDGEMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcknowledgement(@jakarta.annotation.Nullable String acknowledgement) {
    this.acknowledgement = acknowledgement;
  }

  public SlaConfig resolution(@jakarta.annotation.Nullable String resolution) {

    this.resolution = resolution;
    return this;
  }

  /**
   * Time to resolve, counted from case creation, as an ISO-8601 duration (e.g. PT8H).
   * @return resolution
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_RESOLUTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResolution() {
    return resolution;
  }


  @JsonProperty(JSON_PROPERTY_RESOLUTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResolution(@jakarta.annotation.Nullable String resolution) {
    this.resolution = resolution;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SlaConfig slaConfig = (SlaConfig) o;
    return Objects.equals(this.acknowledgement, slaConfig.acknowledgement) &&
        Objects.equals(this.resolution, slaConfig.resolution);
  }

  @Override
  public int hashCode() {
    return Objects.hash(acknowledgement, resolution);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SlaConfig {\n");
    sb.append("    acknowledgement: ").append(toIndentedString(acknowledgement)).append("\n");
    sb.append("    resolution: ").append(toIndentedString(resolution)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

