/*
 * Kestra EE
 * All API operations, except for Superadmin-only endpoints, require a tenant identifier in the HTTP path.<br/> Endpoints designated as Superadmin-only are not tenant-scoped.
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.kestra.sdk.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.kestra.sdk.model.SupportDebugInfoAuthType;
import io.kestra.sdk.model.SupportDebugInfoDeploymentType;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Debug information collected automatically and attached to a support ticket.
 */
@JsonPropertyOrder({
  SupportDebugInfo.JSON_PROPERTY_KESTRA_VERSION,
  SupportDebugInfo.JSON_PROPERTY_LICENSE_ID,
  SupportDebugInfo.JSON_PROPERTY_AUTH_TYPE,
  SupportDebugInfo.JSON_PROPERTY_DEPLOYMENT_TYPE,
  SupportDebugInfo.JSON_PROPERTY_QUEUE_TYPE,
  SupportDebugInfo.JSON_PROPERTY_QUEUE_VERSION,
  SupportDebugInfo.JSON_PROPERTY_STORAGE_TYPE,
  SupportDebugInfo.JSON_PROPERTY_REPOSITORY_TYPE,
  SupportDebugInfo.JSON_PROPERTY_REPOSITORY_VERSION,
  SupportDebugInfo.JSON_PROPERTY_SECRET_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class SupportDebugInfo {
  public static final String JSON_PROPERTY_KESTRA_VERSION = "kestraVersion";
  @jakarta.annotation.Nonnull  private String kestraVersion;

  public static final String JSON_PROPERTY_LICENSE_ID = "licenseId";
  @jakarta.annotation.Nullable  private String licenseId;

  public static final String JSON_PROPERTY_AUTH_TYPE = "authType";
  @jakarta.annotation.Nonnull  private SupportDebugInfoAuthType authType;

  public static final String JSON_PROPERTY_DEPLOYMENT_TYPE = "deploymentType";
  @jakarta.annotation.Nonnull  private SupportDebugInfoDeploymentType deploymentType;

  public static final String JSON_PROPERTY_QUEUE_TYPE = "queueType";
  @jakarta.annotation.Nonnull  private String queueType;

  public static final String JSON_PROPERTY_QUEUE_VERSION = "queueVersion";
  @jakarta.annotation.Nullable  private String queueVersion;

  public static final String JSON_PROPERTY_STORAGE_TYPE = "storageType";
  @jakarta.annotation.Nonnull  private String storageType;

  public static final String JSON_PROPERTY_REPOSITORY_TYPE = "repositoryType";
  @jakarta.annotation.Nonnull  private String repositoryType;

  public static final String JSON_PROPERTY_REPOSITORY_VERSION = "repositoryVersion";
  @jakarta.annotation.Nullable  private String repositoryVersion;

  public static final String JSON_PROPERTY_SECRET_TYPE = "secretType";
  @jakarta.annotation.Nonnull  private String secretType;

  public SupportDebugInfo() {
  }

  public SupportDebugInfo kestraVersion(@jakarta.annotation.Nonnull String kestraVersion) {
    
    this.kestraVersion = kestraVersion;
    return this;
  }

  /**
   * Get kestraVersion
   * @return kestraVersion
   */
  @jakarta.annotation.Nonnull  @JsonProperty(JSON_PROPERTY_KESTRA_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKestraVersion() {
    return kestraVersion;
  }


  @JsonProperty(JSON_PROPERTY_KESTRA_VERSION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKestraVersion(@jakarta.annotation.Nonnull String kestraVersion) {
    this.kestraVersion = kestraVersion;
  }

  public SupportDebugInfo licenseId(@jakarta.annotation.Nullable String licenseId) {
    
    this.licenseId = licenseId;
    return this;
  }

  /**
   * Get licenseId
   * @return licenseId
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_LICENSE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLicenseId() {
    return licenseId;
  }


  @JsonProperty(JSON_PROPERTY_LICENSE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLicenseId(@jakarta.annotation.Nullable String licenseId) {
    this.licenseId = licenseId;
  }

  public SupportDebugInfo authType(@jakarta.annotation.Nonnull SupportDebugInfoAuthType authType) {
    
    this.authType = authType;
    return this;
  }

  /**
   * Get authType
   * @return authType
   */
  @jakarta.annotation.Nonnull  @JsonProperty(JSON_PROPERTY_AUTH_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SupportDebugInfoAuthType getAuthType() {
    return authType;
  }


  @JsonProperty(JSON_PROPERTY_AUTH_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAuthType(@jakarta.annotation.Nonnull SupportDebugInfoAuthType authType) {
    this.authType = authType;
  }

  public SupportDebugInfo deploymentType(@jakarta.annotation.Nonnull SupportDebugInfoDeploymentType deploymentType) {
    
    this.deploymentType = deploymentType;
    return this;
  }

  /**
   * Get deploymentType
   * @return deploymentType
   */
  @jakarta.annotation.Nonnull  @JsonProperty(JSON_PROPERTY_DEPLOYMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SupportDebugInfoDeploymentType getDeploymentType() {
    return deploymentType;
  }


  @JsonProperty(JSON_PROPERTY_DEPLOYMENT_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDeploymentType(@jakarta.annotation.Nonnull SupportDebugInfoDeploymentType deploymentType) {
    this.deploymentType = deploymentType;
  }

  public SupportDebugInfo queueType(@jakarta.annotation.Nonnull String queueType) {
    
    this.queueType = queueType;
    return this;
  }

  /**
   * Get queueType
   * @return queueType
   */
  @jakarta.annotation.Nonnull  @JsonProperty(JSON_PROPERTY_QUEUE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getQueueType() {
    return queueType;
  }


  @JsonProperty(JSON_PROPERTY_QUEUE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setQueueType(@jakarta.annotation.Nonnull String queueType) {
    this.queueType = queueType;
  }

  public SupportDebugInfo queueVersion(@jakarta.annotation.Nullable String queueVersion) {
    
    this.queueVersion = queueVersion;
    return this;
  }

  /**
   * Get queueVersion
   * @return queueVersion
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_QUEUE_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQueueVersion() {
    return queueVersion;
  }


  @JsonProperty(JSON_PROPERTY_QUEUE_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQueueVersion(@jakarta.annotation.Nullable String queueVersion) {
    this.queueVersion = queueVersion;
  }

  public SupportDebugInfo storageType(@jakarta.annotation.Nonnull String storageType) {
    
    this.storageType = storageType;
    return this;
  }

  /**
   * Get storageType
   * @return storageType
   */
  @jakarta.annotation.Nonnull  @JsonProperty(JSON_PROPERTY_STORAGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getStorageType() {
    return storageType;
  }


  @JsonProperty(JSON_PROPERTY_STORAGE_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStorageType(@jakarta.annotation.Nonnull String storageType) {
    this.storageType = storageType;
  }

  public SupportDebugInfo repositoryType(@jakarta.annotation.Nonnull String repositoryType) {
    
    this.repositoryType = repositoryType;
    return this;
  }

  /**
   * Get repositoryType
   * @return repositoryType
   */
  @jakarta.annotation.Nonnull  @JsonProperty(JSON_PROPERTY_REPOSITORY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRepositoryType() {
    return repositoryType;
  }


  @JsonProperty(JSON_PROPERTY_REPOSITORY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRepositoryType(@jakarta.annotation.Nonnull String repositoryType) {
    this.repositoryType = repositoryType;
  }

  public SupportDebugInfo repositoryVersion(@jakarta.annotation.Nullable String repositoryVersion) {
    
    this.repositoryVersion = repositoryVersion;
    return this;
  }

  /**
   * Get repositoryVersion
   * @return repositoryVersion
   */
  @jakarta.annotation.Nullable  @JsonProperty(JSON_PROPERTY_REPOSITORY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRepositoryVersion() {
    return repositoryVersion;
  }


  @JsonProperty(JSON_PROPERTY_REPOSITORY_VERSION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRepositoryVersion(@jakarta.annotation.Nullable String repositoryVersion) {
    this.repositoryVersion = repositoryVersion;
  }

  public SupportDebugInfo secretType(@jakarta.annotation.Nonnull String secretType) {
    
    this.secretType = secretType;
    return this;
  }

  /**
   * Get secretType
   * @return secretType
   */
  @jakarta.annotation.Nonnull  @JsonProperty(JSON_PROPERTY_SECRET_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getSecretType() {
    return secretType;
  }


  @JsonProperty(JSON_PROPERTY_SECRET_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSecretType(@jakarta.annotation.Nonnull String secretType) {
    this.secretType = secretType;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupportDebugInfo supportDebugInfo = (SupportDebugInfo) o;
    return Objects.equals(this.kestraVersion, supportDebugInfo.kestraVersion) &&
        Objects.equals(this.licenseId, supportDebugInfo.licenseId) &&
        Objects.equals(this.authType, supportDebugInfo.authType) &&
        Objects.equals(this.deploymentType, supportDebugInfo.deploymentType) &&
        Objects.equals(this.queueType, supportDebugInfo.queueType) &&
        Objects.equals(this.queueVersion, supportDebugInfo.queueVersion) &&
        Objects.equals(this.storageType, supportDebugInfo.storageType) &&
        Objects.equals(this.repositoryType, supportDebugInfo.repositoryType) &&
        Objects.equals(this.repositoryVersion, supportDebugInfo.repositoryVersion) &&
        Objects.equals(this.secretType, supportDebugInfo.secretType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(kestraVersion, licenseId, authType, deploymentType, queueType, queueVersion, storageType, repositoryType, repositoryVersion, secretType);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupportDebugInfo {\n");
    sb.append("    kestraVersion: ").append(toIndentedString(kestraVersion)).append("\n");
    sb.append("    licenseId: ").append(toIndentedString(licenseId)).append("\n");
    sb.append("    authType: ").append(toIndentedString(authType)).append("\n");
    sb.append("    deploymentType: ").append(toIndentedString(deploymentType)).append("\n");
    sb.append("    queueType: ").append(toIndentedString(queueType)).append("\n");
    sb.append("    queueVersion: ").append(toIndentedString(queueVersion)).append("\n");
    sb.append("    storageType: ").append(toIndentedString(storageType)).append("\n");
    sb.append("    repositoryType: ").append(toIndentedString(repositoryType)).append("\n");
    sb.append("    repositoryVersion: ").append(toIndentedString(repositoryVersion)).append("\n");
    sb.append("    secretType: ").append(toIndentedString(secretType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

