name: GO SDK tests

on:
  workflow_call:
    secrets:
      GOOGLE_SERVICE_ACCOUNT:
        required: true
      GCP_SERVICE_ACCOUNT:
        required: true
      KESTRA_EE_UNIT_TEST_LICENSE_FILE:
        required: false
      KESTRA_EE_UNIT_TEST_LICENSE_LEGACY_FILE:
        required: false
  workflow_dispatch:
    inputs:
      skip-test:
        description: 'Skip test'
        required: false
        type: string
        default: "false"

jobs:
  list-versions:
    uses: ./.github/workflows/list-versions.yml

  test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
    defaults:
      run:
        working-directory: ./go-sdk
    needs: list-versions
    strategy:
      fail-fast: false
      matrix:
        kestra_version: ${{ fromJSON(needs.list-versions.outputs.versions) }}
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-go@v5

      - name: build
        id: build
        run: go build ./...

      - name: GCP - Auth with github service account
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: configure docker access to GCP registry for EE image
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Select license file
        id: license
        uses: ./.github/actions/set-license-file
        with:
          kestra_version: ${{ matrix.kestra_version }}
          license_file: ${{ secrets.KESTRA_EE_UNIT_TEST_LICENSE_FILE }}
          license_legacy_file: ${{ secrets.KESTRA_EE_UNIT_TEST_LICENSE_LEGACY_FILE }}

      - name: Build local SDK and test it in an example project
        if: ${{ github.event.inputs.skip-test == 'false' || github.event.inputs.skip-test == '' }}
        env:
          KESTRA_VERSION: ${{ matrix.kestra_version }}
        run: |
          echo "${{ steps.license.outputs.license }}" | base64 -d > ../test-utils/docker-setup/application-secrets.yml
          sh run-tests.sh $KESTRA_VERSION