name: Python SDK release

on:
  workflow_call:
    inputs:
      kestra_version:
        description: "Kestra version to test against"
        required: false
        type: string
        default: "develop"
    secrets:
      PYPI_API_TOKEN:
        required: true
      GCP_SERVICE_ACCOUNT:
        required: true
      KESTRA_EE_UNIT_TEST_LICENSE_FILE:
        required: true
      KESTRA_EE_UNIT_TEST_LICENSE_LEGACY_FILE:
        required: true
  workflow_dispatch:
    inputs:
      skip-test:
        description: "Skip test"
        required: false
        type: choice
        options:
          - "true"
          - "false"
        default: "false"

jobs:
  test:
    name: Test Python SDK
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/python-sdk
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.23"

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Install tests deps
        run: pip install -r test-requirements.txt

      - name: GCP - Auth with github service account
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: configure docker access to GCP registry for EE image
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Select license file
        id: license
        uses: ./.github/actions/set-license-file
        with:
          kestra_version: ${{ inputs.kestra_version }}
          license_file: ${{ secrets.KESTRA_EE_UNIT_TEST_LICENSE_FILE }}
          license_legacy_file: ${{ secrets.KESTRA_EE_UNIT_TEST_LICENSE_LEGACY_FILE }}

      - name: Test with pytest
        if: ${{ github.event.inputs.skip-test == 'false' ||
          github.event.inputs.skip-test == '' }}
        env:
          KESTRA_VERSION: ${{ inputs.kestra_version }}
        run: |
          echo "${{ steps.license.outputs.license }}" | base64 -d > ../../test-utils/docker-setup/application-secrets.yml
          sh run-tests.sh $KESTRA_VERSION

  publish:
    name: Publish to Pip
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/heads/releases/')
    defaults:
      run:
        working-directory: ./python/python-sdk
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9.23"

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: |
          VERSION=${GITHUB_REF_NAME#releases/v}
          VERSION=$VERSION python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
          packages-dir: python/python-sdk/dist
